export const NAVIGATION_PROGRAM = {
  FACTORY: "FACTORY",
  DEPARTMENTS: "DEPARTMENTS",
  USER: "USER",
  USER_PERMISSION: "USER_PERMISSION",
  PROGRAM: "PROGRAM",
  PROGRAM_FIELD_TITLE: "PROGRAM_FIELD_TITLE",
  BASIC_DATA: "BASIC_DATA",
};

export const NAVIGATION_ITEMS = [
  {
    id: "factory",
    labelKey: "lbl_factory",
    fallbackLabel: "Factory",
    icon: "factory",
    programCode: NAVIGATION_PROGRAM.FACTORY,
  },
  {
    id: "departments",
    labelKey: "lbl_department",
    fallbackLabel: "Departments",
    icon: "department",
    programCode: NAVIGATION_PROGRAM.DEPARTMENTS,
  },
  {
    id: "user",
    labelKey: "lbl_user",
    fallbackLabel: "Users",
    icon: "users",
    programCode: NAVIGATION_PROGRAM.USER,
  },
  {
    id: "permission",
    labelKey: "lbl_permission",
    fallbackLabel: "Permissions",
    icon: "permission",
    programCode: NAVIGATION_PROGRAM.USER_PERMISSION,
  },
  {
    id: "program",
    labelKey: "lbl_program",
    fallbackLabel: "Program",
    icon: "program",
    programCode: NAVIGATION_PROGRAM.PROGRAM,
  },
  {
    id: "language",
    labelKey: "lbl_language",
    fallbackLabel: "Language",
    icon: "language",
    programCode: NAVIGATION_PROGRAM.PROGRAM_FIELD_TITLE,
  },
  {
    id: "bom",
    labelKey: "lbl_ac_bom",
    fallbackLabel: "Customs BOM",
    icon: "bom",
    programCode: "ACTF_020",
    children: [
      { id: "actf_020", labelKey: "lbl_actf_020_1", fallbackLabel: "BOM Item Master", programCode: "ACTF_020" },
      { id: "actf_020_1", labelKey: "lbl_actf_020_2", fallbackLabel: "Material Tracking", programCode: "ACTF_0201" },
      { id: "actf_020_2", labelKey: "lbl_actf_020_3", fallbackLabel: "BOM Structure", programCode: "ACTF_0202" },
      { id: "actf_021", labelKey: "lbl_actf_021", fallbackLabel: "BOM Maintain", programCode: "ACTF_021" },
    ],
  },
  {
    id: "ac_import",
    labelKey: "lbl_ac_import",
    fallbackLabel: "Import",
    icon: "import",
    programCode: "ACTF_410",
    children: [
      { id: "actf_250", labelKey: "lbl_actf_250", fallbackLabel: "Import Material Tracking", programCode: "ACTF_250" },
      { id: "actf_410", labelKey: "lbl_actf_410", fallbackLabel: "Customs Declaration Application", programCode: "ACTF_410" },
      { id: "actf_410_1", labelKey: "lbl_actf_410_1", fallbackLabel: "Material Tracking", programCode: "ACTF_410" },
      { id: "actf_410_2", labelKey: "lbl_actf_410_2", fallbackLabel: "Customs Tracking", programCode: "ACTF_4102" },
      { id: "actf_110", labelKey: "lbl_actf_110", fallbackLabel: "Import Contract", programCode: "ACTF_110" },
      { id: "actf_130", labelKey: "lbl_actf_130", fallbackLabel: "INM Master", programCode: "ACTF_130" },
      { id: "actf_210", labelKey: "lbl_actf_210", fallbackLabel: "Create Foreign Import Declaration", programCode: "ACTF_210" },
      { id: "actf_220", labelKey: "lbl_actf_220", fallbackLabel: "Create Transfer Import Declaration", programCode: "ACTF_220" },
    ],
  },
  {
    id: "ac_export",
    labelKey: "lbl_ac_export",
    fallbackLabel: "Export",
    icon: "export",
    programCode: "SETF_570",
    children: [
      { id: "setf_570", labelKey: "lbl_setf_570", fallbackLabel: "Customs Declaration Application", programCode: "SETF_570" },
      { id: "setf_560", labelKey: "lbl_setf_560", fallbackLabel: "Customs Declaration Application 560", programCode: "SETF_560" },
      { id: "actf_230", labelKey: "lbl_actf_230", fallbackLabel: "Customs Declaration Application 230", programCode: "ACTF_230" },
      { id: "setf_590", labelKey: "lbl_setf_590", fallbackLabel: "Customs Declaration Application 590", programCode: "SETF_590" },
      { id: "setf_590_1", labelKey: "lbl_setf_590_1", fallbackLabel: "Customs Declaration Application 5901", programCode: "SETF_5901" },
      { id: "actf_240", labelKey: "lbl_actf_240", fallbackLabel: "Customs Declaration Application 240", programCode: "ACTF_240" },
    ],
  },
  {
    id: "ac_other",
    labelKey: "lbl_ac_other",
    fallbackLabel: "Other",
    icon: "other",
    programCode: NAVIGATION_PROGRAM.BASIC_DATA,
    children: [
      { id: "basic_data", labelKey: "lbl_basic_data", fallbackLabel: "Basic Data", programCode: NAVIGATION_PROGRAM.BASIC_DATA },
      { id: "actf_290", labelKey: "lbl_actf_290", fallbackLabel: "Customs Declaration Application", programCode: "ACTF_290" },
      { id: "actf_120", labelKey: "lbl_actf_120", fallbackLabel: "Customs Declaration Application 120", programCode: "ACTF_120" },
      { id: "actf_120_1", labelKey: "lbl_actf_1201", fallbackLabel: "Customs Declaration Application 1201", programCode: "ACTF_1201" },
      { id: "setf_120", labelKey: "lbl_setf_120", fallbackLabel: "Customs Declaration Application S120", programCode: "SETF_120" },
      { id: "actf_310", labelKey: "lbl_actf_310", fallbackLabel: "Customs Declaration Application 310", programCode: "ACTF_310" },
      { id: "actf_310_1", labelKey: "lbl_actf_3101", fallbackLabel: "Customs Declaration Application 3101", programCode: "ACTF_3101" },
      { id: "setf_510", labelKey: "lbl_setf_510", fallbackLabel: "Customs Declaration Application 510", programCode: "SETF_510" },
      { id: "actf_270", labelKey: "lbl_actf_270", fallbackLabel: "Customs Declaration Application 270", programCode: "ACTF_270" },
      { id: "actf_022", labelKey: "lbl_actf_022", fallbackLabel: "Customs Declaration Application 022", programCode: "ACTF_022" },
    ],
  },
];

export const getNavigationPath = (item) => `/${item.id.toLowerCase()}`;
