const Joi = require("joi");

const createAcImpMaterialTrackingSchema = Joi.object({
  factory_code: Joi.string().max(20).required(),
  invoice_no: Joi.string().max(20).required(),
  sort: Joi.string().max(20).required(),
  declaration_category: Joi.string().max(30).allow(null).empty('').default(null).optional(),
  record_date: Joi.date().allow(null).empty('').default(null).optional(),
  loading_way: Joi.string().max(30).allow(null).empty('').default(null).optional(),
  exporting_countries: Joi.string().max(30).allow(null).empty('').default(null).optional(),
  b_l: Joi.string().allow(null).empty('').default(null).optional(),
  loading_port: Joi.string().max(30).allow(null).empty('').default(null).optional(),
  unloading_port: Joi.string().max(30).allow(null).empty('').default(null).optional(),
  shipside: Joi.string().max(30).allow(null).empty('').default(null).optional(),
  bill_of_lading_no: Joi.string().max(30).allow(null).empty('').default(null).optional(),
  departure_date: Joi.date().allow(null).empty('').default(null).optional(),
  estimated_arrival_date: Joi.date().allow(null).empty('').default(null).optional(),
  actual_arrival_date: Joi.date().allow(null).empty('').default(null).optional(),
  estimated_delivery_date: Joi.date().allow(null).empty('').default(null).optional(),
  actual_delivery_date: Joi.date().allow(null).empty('').default(null).optional(),
  date_completion_procedures: Joi.date().allow(null).empty('').default(null).optional(),
  declaration_retrieve_date: Joi.date().allow(null).empty('').default(null).optional(),
  invoice_amount: Joi.number().allow(null).empty('').default(null).optional(),
  currency: Joi.string().max(30).allow(null).empty('').default(null).optional(),
  exchange_rate: Joi.number().allow(null).empty('').default(null).optional(),
  qty_of_pieces: Joi.number().allow(null).empty('').default(null).optional(),
  gross_weight: Joi.number().allow(null).empty('').default(null).optional(),
  packaging_unit: Joi.string().max(30).allow(null).empty('').default(null).optional(),
  container_quantity: Joi.number().allow(null).empty('').default(null).optional(),
  material_description: Joi.string().max(600).allow(null).empty('').default(null).optional(),
  factory_materials: Joi.string().max(600).allow(null).empty('').default(null).optional(),
  shipping_payment_way: Joi.string().max(600).allow(null).empty('').default(null).optional(),
  import_delay_reason: Joi.string().max(600).allow(null).empty('').default(null).optional(),
  is_ac: Joi.string().max(1).allow(null).empty('').default(null).optional(),
  status: Joi.number().integer().default(1).optional(),
  grt_dept: Joi.string().max(600).allow(null).empty('').default(null).optional(),
  grt_user: Joi.string().max(600).allow(null).empty('').default(null).optional(),
  grt_date: Joi.date().allow(null).empty('').default(null).optional(),
  last_user: Joi.string().max(20).allow(null).empty('').default(null).optional(),
  last_date: Joi.date().allow(null).empty('').default(null).optional(),
  locked_information: Joi.string().max(600).allow(null).empty('').default(null).optional(),
});

module.exports = createAcImpMaterialTrackingSchema;
