const TableColumns = {
  AC_SHOE_M: [
    { field: "customs_shoe_id", headerName: "customs_shoe_id", width: 200 },
    {
      field: "customs_shoe_name_l",
      headerName: "customs_shoe_name_l",
      width: 200,
    },
    {
      field: "customs_shoe_name_t",
      headerName: "customs_shoe_name_t",
      width: 200,
    },
    {
      field: "customs_shoe_name_e",
      headerName: "customs_shoe_name_e",
      width: 200,
    },
    { field: "customs_tariff", headerName: "customs_tariff", width: 200 },
    { field: "size_type", headerName: "size_type", width: 200 },
    { field: "unit", headerName: "unit", width: 200 },
    {
      field: "locked_information",
      headerName: "Lock Information",
      width: 175,
    },
    { field: "status", headerName: "status", width: 200 },
  ],
  AC_SHOE_REF: [
    { field: "prod_no", headerName: "prod_no", width: 70 },
    { field: "prod_unit", headerName: "prod_unit", width: 70 },
    { field: "is_valid", headerName: "is_valid", width: 30 },
    { field: "valid_date", headerName: "valid_date", width: 100 },
    { field: "unval_date", headerName: "unval_date", width: 100 },
    {
      field: "locked_information",
      headerName: "Lock Information",
      width: 80,
    },
    { field: "status", headerName: "status", width: 118 },
  ],
  AC_PROD_M: [
    { field: "prod_acno", headerName: "prod_acno", width: 140 },
    { field: "start_size", headerName: "start_size", width: 140 },
    { field: "s_seq", headerName: "s_seq", width: 140 },
    { field: "end_size", headerName: "end_size", width: 140 },
    { field: "e_seq", headerName: "e_seq", width: 140 },
    { field: "pt_per", headerName: "pt_per", width: 140 },
    { field: "note", headerName: "note", width: 140 },
    { field: "bang_ke_size", headerName: "Bang Ke Size", width: 131 },
    {
      field: "locked_information",
      headerName: "Lock Information",
      width: 135,
    },
    { field: "status", headerName: "status", width: 130 },
  ],
  AC_BOM_M: [
    { field: "prod_acno", headerName: "prod_acno", width: 200 },
    { field: "item_acno", headerName: "item_acno", width: 165 },
    { field: "unit_qty", headerName: "unit_qty", width: 160 },
    { field: "loss_per", headerName: "loss_per", width: 160 },
    { field: "note", headerName: "note", width: 160 },
    { field: "fact_qty", headerName: "fact_qty", width: 160 },
    { field: "ac_type", headerName: "ac_type", width: 160 },
    {
      field: "locked_information",
      headerName: "Lock Information",
      width: 160,
    },
    { field: "status", headerName: "status", width: 160 },
  ],
  AC_ITEM_REF: [
    { field: "item_no", headerName: "item_no", width: 365 },
    { field: "item_unit", headerName: "item_unit", width: 280 },
    { field: "formula", headerName: "formula", width: 280 },
    {
      field: "locked_information",
      headerName: "Lock Information",
      width: 280,
    },
    { field: "status", headerName: "status", width: 280 },
  ],
  AC_ITEM_M: [
    { field: "item_acno", headerName: "item_acno", width: 200 },
    { field: "item_acname_l", headerName: "item_acname_l", width: 200 },
    { field: "item_acname_t", headerName: "item_acname_t", width: 200 },
    { field: "item_acname_e", headerName: "item_acname_e", width: 200 },
    { field: "ac_item", headerName: "ac_item", width: 150 },
    { field: "unit", headerName: "unit", width: 150 },
    { field: "tax_per", headerName: "tax_per", width: 150 },
    { field: "loss_per", headerName: "loss_per", width: 150 },
    { field: "ac_type", headerName: "ac_type", width: 150 },
    {
      field: "locked_information",
      headerName: "Lock Information",
      width: 155,
    },
    { field: "status", headerName: "status", width: 180 },
  ],
  USER: [
    // { field: "factory_code", headerName: "factory_code", width: 70 },
    // { field: "department_code", headerName: "department_code", width: 70 },
    { field: "user_code", headerName: "user_code", width: 120 },
    { field: "user_name_t", headerName: "user_name_t", width: 150 },
    { field: "user_name_e", headerName: "user_name_e", width: 150 },
    { field: "user_name_l", headerName: "user_name_l", width: 150 },
    { field: "supervisor_id", headerName: "supervisor_id", width: 160 },
    {
      field: "allow_authorization",
      headerName: "allow_authorization",
      width: 130,
    },
    { field: "status", headerName: "status", width: 130 },
  ],
  USER_PERMISSION: [
    { field: "program_code", headerName: "program_code", width: 100 },
    { field: "query_level", headerName: "query_level", width: 125 },
    { field: "modify_level", headerName: "modify_level", width: 125 },
    { field: "allow_query", headerName: "allow_query", width: 80 },
    { field: "allow_add", headerName: "allow_add", width: 80 },
    { field: "allow_delete", headerName: "allow_delete", width: 80 },
    { field: "allow_modify", headerName: "allow_modify", width: 80 },
    { field: "allow_cancel", headerName: "allow_cancel", width: 80 },
    { field: "allow_confirm", headerName: "allow_confirm", width: 80 },
    { field: "allow_unconfirm", headerName: "allow_unconfirm", width: 80 },
    { field: "allow_close", headerName: "allow_close", width: 80 },
    { field: "allow_check", headerName: "allow_check", width: 80 },
    { field: "allow_uncheck", headerName: "allow_uncheck", width: 80 },
    { field: "status", headerName: "status", width: 85 },
  ],
  FACTORY: [
    {
      field: "factory_code",
      headerName: "factory_code",
      width: 200,
      minWidth: 120,
      maxWidth: 200,
    },
    { field: "factory_name_t", headerName: "factory_name_t", width: 200 },
    { field: "factory_name_e", headerName: "factory_name_e", width: 200 },
    { field: "factory_name_l", headerName: "factory_name_l", width: 200 },
    { field: "factory_address", headerName: "factory_address", width: 200 },
    {
      field: "factory_abbreviation",
      headerName: "factory_abbreviation",
      width: 240,
    },
    { field: "factory_tax_no", headerName: "factory_tax_no", width: 220 },
    {field: "locked_information", headerName: "Lock Information", width: 200, },
    { field: "status", headerName: "status", width: 225 },
  ],
  DEPARTMENTS: [
    { field: "department_code", headerName: "department_code", width: 243 },
    { field: "department_name_t", headerName: "department_name_t", width: 240 },
    { field: "department_name_e", headerName: "department_name_e", width: 250 },
    { field: "department_name_l", headerName: "department_name_l", width: 255 },
    { field: "status", headerName: "status", width: 250 },
  ],
  USER_PERMISSION_DEPARTMENT: [
    {
      field: "factory_code",
      headerName: "factory_code",
      width: 220,
      minWidth: 120,
    },
    {
      field: "factory_name",
      headerName: "factory_name",
      width: 260,
      minWidth: 120,
    },
    {
      field: "department_code",
      headerName: "department_code",
      width: 220,
      minWidth: 120,
    },
    {
      field: "department_name",
      headerName: "department_name",
      width: 260,
      minWidth: 120,
    },
    {
      field: "status",
      headerName: "Status",
      width: 275,
      minWidth: 120,
    },
  ],
  PROGRAM: [
    {
      field: "program_code",
      headerName: "program_code",
      width: 300,
      minWidth: 120,
      maxWidth: 350,
    },
    { field: "program_name_t", headerName: "program_name_t", width: 300 },
    { field: "program_name_e", headerName: "program_name_e", width: 300 },
    { field: "program_name_l", headerName: "program_name_l", width: 300 },
    { field: "status", headerName: "status", width: 286 },
  ],
  PROGRAM_FIELD_TITLE: [
    {
      field: "field_code",
      headerName: "field_code",
      width: 250,
      minWidth: 120,
      maxWidth: 350,
    },
    { field: "title_name_t", headerName: "title_name_t", width: 250 },
    { field: "title_name_e", headerName: "title_name_e", width: 250 },
    { field: "title_name_l", headerName: "title_name_l", width: 248 },
    { field: "status", headerName: "status", width: 240 },
  ],
  BASIC_DATA_CATEGORY: [
    {
      field: "category_code",
      headerName: "category_code",
      width: 285,
      minWidth: 120,
      maxWidth: 350,
    },
    { field: "category_name_t", headerName: "category_name_t", width: 400 },
    { field: "category_name_e", headerName: "category_name_e", width: 400 },
    { field: "category_name_l", headerName: "category_name_l", width: 400 },
    {
      field: "locked_information",
      headerName: "Locked Information",
      width: 400,
    },
    { field: "status", headerName: "status", width: 400 },
  ],
  BASIC_DATA: [
    {
      field: "code_no",
      headerName: "code_no",
      width: 285,
      minWidth: 120,
      maxWidth: 300,
    },
    { field: "name_t", headerName: "name_t", width: 400 },
    { field: "name_e", headerName: "name_e", width: 400 },
    { field: "name_l", headerName: "name_l", width: 400 },
    {
      field: "locked_information",
      headerName: "Locked Information",
      width: 400,
    },
    { field: "status", headerName: "status", width: 400 },
  ],
  AC_IMP_MATERIAL_TRACKING: [
    {
      field: "invoice_no",
      headerName: "invoice_no",
      width: 91,
    },
    {
      field: "sort",
      headerName: "sort",
      width: 50,
    },
    {
      field: "declaration_category_name",
      headerName: "declaration_category_name",
      width: 91,
    },
    {
      field: "record_date",
      headerName: "record_date",
      width: 120,
    },
    {
      field: "loading_way",
      headerName: "loading_way",
      width: 120,
    },
    {
      field: "exporting_countries",
      headerName: "exporting_countries",
      width: 120,
    },
    {
      field: "b_l",
      headerName: "b_l",
      width: 120,
    },
    {
      field: "loading_port",
      headerName: "loading_port",
      width: 120,
    },
    {
      field: "unloading_port",
      headerName: "unloading_port",
      width: 120,
    },
    {
      field: "bill_of_lading_no",
      headerName: "bill_of_lading_no",
      width: 120,
    },
    {
      field: "shipside",
      headerName: "shipside",
      width: 120,
    },
    {
      field: "departure_date",
      headerName: "departure_date",
      width: 120,
    },
    {
      field: "estimated_arrival_date",
      headerName: "estimated_arrival_date",
      width: 120,
    },
    {
      field: "actual_arrival_date",
      headerName: "actual_arrival_date",
      width: 120,
    },
    {
      field: "actual_delivery_date",
      headerName: "actual_delivery_date",
      width: 120,
    },
    {
      field: "estimated_delivery_date",
      headerName: "estimated_delivery_date",
      width: 120,
    },
    {
      field: "invoice_amount",
      headerName: "invoice_amount",
      width: 120,
    },
    {
      field: "currency",
      headerName: "currency",
      width: 120,
    },
    {
      field: "exchange_rate",
      headerName: "exchange_rate",
      width: 120,
    },
    {
      field: "qty_of_pieces",
      headerName: "qty_of_pieces",
      width: 120,
    },
    {
      field: "gross_weight",
      headerName: "gross_weight",
      width: 120,
    },
    {
      field: "packaging_unit",
      headerName: "packaging_unit",
      width: 120,
    },
    {
      field: "material_description",
      headerName: "material_description",
      width: 120,
    },
    {
      field: "factory_materials",
      headerName: "factory_materials",
      width: 120,
    },
    {
      field: "shipping_payment_way",
      headerName: "shipping_payment_way",
      width: 120,
    },
    {
      field: "import_delay_reason",
      headerName: "import_delay_reason",
      width: 120,
    },
    {
      field: "container_quantity",
      headerName: "container_quantity",
      width: 120,
    },
    {
      field: "date_completion_procedures",
      headerName: "date_completion_procedures",
      width: 120,
    },
    {
      field: "declaration_retrieve_date",
      headerName: "declaration_retrieve_date",
      width: 120,
    },
    {
      field: "is_ac",
      headerName: "is_ac",
      width: 120,
    },
    {
      field: "locked_information",
      headerName: "Lock Information",
      width: 120,
    },
    { field: "status", headerName: "status", width: 120 },
  ],
  RD_SIZE_D: [
    {
      field: "size_no",
      headerName: "size_no",
      width: 835,
    },
  ],
  VW_AC_SHOEBOM: [
    { field: "customs_shoe_id", headerName: "customs_shoe_id", width: 100 },
    { field: "customs_tariff", headerName: "customs_tariff", width: 100 },
    { field: "size_type", headerName: "size_type", width: 100 },
    { field: "shoe_unit", headerName: "shoe_unit", width: 100 },
    { field: "prod_acno", headerName: "prod_acno", width: 100 },
    { field: "start_size", headerName: "start_size", width: 100 },
    { field: "s_seq", headerName: "s_seq", width: 100 },
    { field: "end_size", headerName: "end_size", width: 100 },
    { field: "e_seq", headerName: "e_seq", width: 100 },
    { field: "pt_per", headerName: "pt_per", width: 100 },
    { field: "item_acno", headerName: "item_acno", width: 100 },
    { field: "loss_per", headerName: "loss_per", width: 100 },
    { field: "unit_qty", headerName: "unit_qty", width: 100 },
    { field: "fact_qty", headerName: "fact_qty", width: 95 },
    { field: "status", headerName: "status", width: 90 },
  ],
  AC_VEND_BASE: [
    { field: "vend_no", headerName: "vend_no", width: 250 },
    { field: "ac_send", headerName: "ac_send", width: 250 },
    { field: "is_default", headerName: "is_default", width: 250 },
    { field: "req_qc", headerName: "req_qc", width: 250 },
    {
      field: "locked_information",
      headerName: "Lock Information",
      width: 200,
    },
    { field: "status", headerName: "status", width: 200 },
  ],
  AC_SEND_BASE: [
    { field: "ac_send", headerName: "ac_send", width: 250 },
    { field: "ac_type_name", headerName: "ac_type", width: 250 },
    { field: "stoc_type_name", headerName: "stoc_type", width: 250 },
    { field: "sales_type_name", headerName: "sales_type", width: 250 },
    {
      field: "locked_information",
      headerName: "Lock Information",
      width: 200,
    },
    { field: "status", headerName: "status", width: 200 },
  ],
  AC_REQ_M: [
    { field: "req_no", headerName: "req_no", width: 250 },
    { field: "req_date", headerName: "req_date", width: 250 },
    { field: "invoice_no", headerName: "invoice_no", width: 250 },
    { field: "ac_no", headerName: "ac_no", width: 250 },
    { field: "ac_type_name", headerName: "ac_type", width: 250 },
    { field: "vend_no_name", headerName: "vend_no", width: 250 },
    {
      field: "locked_information",
      headerName: "Lock Information",
      width: 235,
    },
    { field: "status", headerName: "status", width: 200 },
  ],
  AC_REQ_ORDER: [
    { field: "req_seq", headerName: "Req Seq", width: 100 },
    { field: "src_id", headerName: "Src ID", width: 100 },
    { field: "order_type", headerName: "Order Type", width: 100 },
    { field: "order_date", headerName: "Order Date", width: 100 },
    { field: "order_no", headerName: "Order No", width: 100 },
    { field: "order_seq", headerName: "Order Seq", width: 100 },
    { field: "ac_send", headerName: "Ac Send", width: 100 },
    { field: "cont_no", headerName: "Cont no", width: 100 },
    { field: "ac_no", headerName: "AC No", width: 100 },
    { field: "ac_code", headerName: "AC Code", width: 100 },
    { field: "item_acno", headerName: "Item Acno", width: 100 },
    { field: "order_acqty", headerName: "Order Qty", width: 100 },
    { field: "req_acqty", headerName: "req acqty", width: 100 },
    { field: "chge_qty", headerName: "Chge Qty", width: 100 },
    { field: "rcpt_qty", headerName: "Rcpt Qty", width: 100 },
    { field: "pass_qty", headerName: "Pass Qty", width: 100 },
    { field: "req_qty", headerName: "Req Qty", width: 100 },
    { field: "currency", headerName: "Currency", width: 100 },
    { field: "price", headerName: "Price", width: 100 },
    { field: "amount", headerName: "Amount", width: 100 },
    { field: "chk_no", headerName: "Chk No", width: 100 },
    { field: "chk_seq", headerName: "Chk Seq", width: 100 },
    {
      field: "locked_information",
      headerName: "Lock Information",
      width: 100,
    },
    { field: "status", headerName: "Status", width: 100 },
    { field: "req_qc", headerName: "Req Qc", width: 100 },
  ],
  AC_SRCORDER_M: [
    { field: "id", headerName: "Id", width: 120 },
    { field: "order_type", headerName: "Order Type", width: 120 },
    { field: "order_date", headerName: "Order Date", width: 150 },
    { field: "vr_cfmday", headerName: "Vendor Confirm Day", width: 80 },
    { field: "order_no", headerName: "Order No", width: 180 },
    { field: "order_seq", headerName: "Order Seq", width: 120 },
    { field: "vend_no", headerName: "Vend No", width: 150 },
    { field: "pr_unit", headerName: "Pr Unit", width: 150 },
    { field: "pr_formula", headerName: "Pr Formula", width: 150 },
    { field: "ac_send", headerName: "AC Send", width: 150 },
    { field: "ac_vend", headerName: "AC Vend", width: 150 },
    { field: "cont_no", headerName: "Container No", width: 200 },
    { field: "ac_code", headerName: "AC Code", width: 150 },
    { field: "plan_seq", headerName: "Plan Seq", width: 150 },
    { field: "item_acno", headerName: "Item AC No", width: 150 },
    { field: "order_acqty", headerName: "Order AC Qty", width: 130 },
    { field: "order_qty", headerName: "Order Qty", width: 130 },
    { field: "req_acqty", headerName: "Req AC Qty", width: 130 },
    { field: "req_ac", headerName: "Req AC", width: 130 },
    { field: "chge_qty", headerName: "Change Qty", width: 130 },
    // { field: "rcpt_qty", headerName: "Receipt Qty", width: 130 },
    { field: "pass_qty", headerName: "Pass Qty", width: 130 },
    // { field: "req_qc", headerName: "Req QC", width: 100 },
    // { field: "req_qty", headerName: "Req Qty", width: 120 },
    { field: "currency", headerName: "Currency", width: 100 },
    { field: "price", headerName: "Price", width: 120 },
    { field: "amount", headerName: "Amount", width: 120 },
    { field: "chge_ordqty", headerName: "chge_ordqty", width: 80 },
    {
      field: "locked_information",
      headerName: "Lock Information",
      width: 235,
    },
    { field: "status", headerName: "Status", width: 100 },
  ],
  VW_AC_SRCORDER: [
    { field: "order_date", headerName: "Order Date", width: 120 },
    { field: "order_no", headerName: "Order No", width: 116 },
    { field: "order_seq", headerName: "Order Seq", width: 120 },
    { field: "vr_cfmday", headerName: "Vendor Confirm Day", width: 120 },
    { field: "ac_code", headerName: "AC Code", width: 120 },
    { field: "item_acno", headerName: "item_acno", width: 120 },
    //  { field: "cont_no", headerName: "cont_no", width: 100 },
    //  { field: "order_acqty", headerName: "order_acqty", width: 120 },
    //  { field: "req_acqty", headerName: "req_acqty", width: 80 },
    { field: "order_qty", headerName: "order_qty", width: 80 },
    { field: "chge_ordqty", headerName: "chge_ordqty", width: 120 },
    { field: "plan_iqty", headerName: "plan_iqty", width: 120 },
    { field: "bl_qty", headerName: "bl_qty", width: 100 },
  ],
  VW_AC_ALLCHK: [
    { field: "chk_seq", headerName: "Seq", width: 130 },
    { field: "chk_no", headerName: "Check No", width: 130 },
    { field: "rcpt_date", headerName: "Receipt Date", width: 140 },
    { field: "order_no", headerName: "Order No", width: 130 },
    { field: "order_seq", headerName: "Order Seq", width: 130 },
    { field: "ac_code", headerName: "Item Code", width: 130 },
    { field: "item_acno", headerName: "AC Item No", width: 125 },
    { field: "unitnm", headerName: "Unit", width: 130 },
    { field: "pr_formula", headerName: "Formula", width: 128, type: "number" },
    {
      field: "rcpt_qty",
      headerName: "Receipt Qty",
      width: 130,
      type: "number",
    },
    { field: "cont_no", headerName: "Cont No", width: 130 },
    { field: "ac_send", headerName: "Vendor", width: 130 },
    { field: "bl_qty", headerName: "bl_QTY", width: 130 },
  ],
  IV_TRANS_D_TW: [
    { field: "out_qty", headerName: "Out Qty", width: 240 },
    { field: "last_date", headerName: "Last Date", width: 240 },
  ],
  VW_CONT_IMP: [
    { field: "cont_no", headerName: "cont_no", width: 120 },
    { field: "cont_category_name", headerName: "Category", width: 120 },
    { field: "issued_date", headerName: "issued_date", width: 120 },
    { field: "expire_date", headerName: "expire_date", width: 120 },
    { field: "last_edate", headerName: "last_edate", width: 120 },
    { field: "seller", headerName: "seller", width: 120 },
    { field: "buyer", headerName: "buyer", width: 125 },
    { field: "sum_money", headerName: "sum_money", width: 130 },
    { field: "currency", headerName: "currency", width: 120 },
    { field: "currencynm", headerName: "currency_name", width: 120 },
    { field: "locked_information", headerName: "Lock Information", width: 120 },
    { field: "status", headerName: "status", width: 150 },
  ],
  VW_CONT_IMP_1: [
    { field: "cont_no", headerName: "cont_no", width: 150 },
    { field: "cont_category", headerName: "cont_category", width: 176 },
    { field: "issued_date", headerName: "issued_date", width: 180 },
    { field: "expire_date", headerName: "expire_date", width: 180 },
    { field: "d_type", headerName: "d_type", width: 150 },
    { field: "big_contno", headerName: "big_contno", width: 150 },
    { field: "last_edate", headerName: "last_edate", width: 180 },
    { field: "bvend_no", headerName: "bvend_no", width: 150 },
    { field: "vend_no", headerName: "vend_no", width: 150 },
    { field: "seller", headerName: "seller", width: 200 },
    { field: "s_addr", headerName: "s_addr", width: 300 },
    { field: "s_pic", headerName: "s_pic", width: 200 },
    { field: "s_position", headerName: "s_position", width: 150 },
    { field: "s_accno", headerName: "s_accno", width: 150 },
    { field: "p_seller", headerName: "p_seller", width: 150 },
    { field: "bank", headerName: "bank", width: 200 },
    { field: "bank_ic", headerName: "bank_ic", width: 150 },
    { field: "bank_addr", headerName: "bank_addr", width: 300 },
    { field: "currency", headerName: "currency", width: 100 },
    { field: "currencynm", headerName: "currencynm", width: 150 },
    { field: "term_pay", headerName: "term_pay", width: 100 },
    { field: "term_paynm", headerName: "term_paynm", width: 200 },
    { field: "pay_term", headerName: "pay_term", width: 100 },
    { field: "freight", headerName: "freight", width: 150 },
    { field: "insurance", headerName: "insurance", width: 150 },
    { field: "goods_origin", headerName: "goods_origin", width: 150 },
    { field: "sum_qty", headerName: "sum_qty", width: 150 },
    { field: "sum_money", headerName: "sum_money", width: 150 },
    { field: "note", headerName: "note", width: 300 },
    { field: "last_usernm", headerName: "last_usernm", width: 200 },
    { field: "grt_deptnm", headerName: "grt_deptnm", width: 200 },
    { field: "grt_usernm", headerName: "grt_usernm", width: 200 },
    { field: "status", headerName: "status", width: 100 },
  ],
  AC_CONT_D: [
    { field: "seq", headerName: "Seq", width: 100 },
    { field: "goods_code", headerName: "Goods Code", width: 120 },
    { field: "goods_name", headerName: "Goods Name", width: 125 },
    { field: "unit_code", headerName: "Unit", width: 130 },
    { field: "unit_name", headerName: "Unit Name", width: 130 },
    { field: "cont_qty", headerName: "Contract Qty", width: 130 },
    { field: "cont_price", headerName: "Contract Price", width: 150 },
    { field: "used_qty", headerName: "Used Qty", width: 150 },
    { field: "stock_qty", headerName: "Stock Qty", width: 150 },
    {
      field: "locked_information",
      headerName: "Lock Information",
      width: 200,
    },
    { field: "status", headerName: "status", width: 100 },
  ],
  VW_CONT_USE: [
    { field: "mincont", headerName: "Min Cont", width: 120 },
    { field: "ac_no", headerName: "AC No", width: 120 },
    { field: "ac_chgno", headerName: "AC Chg No", width: 120 },
    { field: "ac_date", headerName: "AC Date", width: 150 },
    { field: "seq", headerName: "Seq", width: 100 },
    { field: "ac_itemno", headerName: "Item No", width: 150 },
    { field: "ac_itemname", headerName: "Item Name", width: 150 },
    { field: "unit", headerName: "Unit", width: 125 },
    { field: "unit_name", headerName: "Unit Name", width: 150 },
    { field: "qty", headerName: "Quantity", width: 150 },
    { field: "money", headerName: "Amount", width: 150 },
  ],
  AC_INM_M: [
    { field: "inm_no", headerName: "INM No", width: 150 },
    { field: "issued_date", headerName: "Issued Date", width: 150 },
    { field: "expire_date", headerName: "Expire Date", width: 150 },
    { field: "req_no", headerName: "Req No", width: 150 },
    { field: "commno", headerName: "Comm No", width: 150 },
    { field: "note", headerName: "Note", width: 250 },
    {
      field: "locked_information",
      headerName: "Lock Information",
      width: 235,
    },
    { field: "status", headerName: "Status", width: 250 },
  ],
  AC_INM_D: [
    { field: "seq", headerName: "Seq", width: 150 },
    { field: "item_no", headerName: "Item No", width: 170 },
    { field: "in_unit", headerName: "In Unit", width: 170 },
    { field: "in_qty", headerName: "In Qty", width: 160 },
    { field: "in_money", headerName: "In Money", width: 150 },
    { field: "hs_qty", headerName: "HS Qty", width: 150 },
    { field: "n_qty", headerName: "N Qty", width: 150 },
    {
      field: "locked_information",
      headerName: "Lock Information",
      width: 235,
    },
    { field: "status", headerName: "Status", width: 150 },
  ],
  VW_CHG_M: [
    { field: "ac_no", headerName: "AC No", width: 120 },
    { field: "ac_type", headerName: "AC Type", width: 100 },
    { field: "ac_unit", headerName: "AC Unit", width: 120 },
    { field: "d_type_name", headerName: "D Type", width: 180 },
    { field: "ac_addr", headerName: "AC Address", width: 150 },
    { field: "deliver", headerName: "Deliver", width: 120 },
    { field: "out_date", headerName: "Out Date", width: 120 },
    { field: "trans_date", headerName: "Trans Date", width: 120 },
    { field: "stoc_type_name", headerName: "Stock Type", width: 150 },
    { field: "ac_chgs", headerName: "AC CHGS", width: 120 },
    { field: "ac_chgno", headerName: "AC CHG No", width: 150 },
    { field: "ac_chgn", headerName: "AC CHGN", width: 120 },
    { field: "ac_chgo", headerName: "AC CHGO", width: 120 },
    { field: "cont_no", headerName: "Cont No", width: 150 },
    { field: "issued_date", headerName: "Issue Date", width: 120 },
    { field: "expire_date", headerName: "Expire Date", width: 120 },
    { field: "vend_no", headerName: "Vendor No", width: 120 },
    { field: "vend_noname", headerName: "Vendor Name", width: 200 },
    { field: "last_edate", headerName: "Last E Date", width: 120 },
    { field: "org_taxnm", headerName: "Org Tax Name", width: 200 },
    { field: "min_cont", headerName: "Min Cont", width: 120 },
    { field: "out_country", headerName: "Out Country", width: 120 },
    { field: "in_port", headerName: "In Port", width: 120 },
    { field: "unload_port", headerName: "Unload Port", width: 150 },
    { field: "soso", headerName: "SOSO", width: 100 },
    { field: "lation", headerName: "Lation", width: 120 },
    { field: "js_no", headerName: "JS No", width: 120 },
    { field: "js_date", headerName: "JS Date", width: 120 },
    { field: "grt_deptname", headerName: "Dept Name", width: 180 },
    { field: "grt_username", headerName: "User Name", width: 180 },
    { field: "last_username", headerName: "Last User Name", width: 180 },
    { field: "curr_no", headerName: "Currency No", width: 120 },
    { field: "currnm", headerName: "Currency Name", width: 150 },
    { field: "com_invoice", headerName: "Com Invoice", width: 150 },
    { field: "gross", headerName: "Gross", width: 120 },
    { field: "sum_money", headerName: "Sum Money", width: 150 },
    { field: "tax", headerName: "Tax", width: 120 },
    {
      field: "locked_information",
      headerName: "Lock Information",
      width: 235,
    },
    { field: "status", headerName: "Status", width: 120 },
  ],
  AC_CHG_D: [
    { field: "seq", headerName: "Seq", width: 100 },
    { field: "ac_itemno", headerName: "Item No", width: 150 },
    { field: "ac_itemnm", headerName: "Item Name", width: 200 },
    { field: "unit", headerName: "Unit", width: 100 },
    { field: "unitnm", headerName: "Unit Name", width: 150 },
    { field: "colornm", headerName: "Color Name", width: 150 },
    { field: "ac_item", headerName: "AC Item", width: 150 },
    { field: "country", headerName: "Country", width: 120 },
    { field: "countrynm", headerName: "Country Name", width: 180 },
    { field: "ref_price", headerName: "Ref Price", width: 120 },
    { field: "price", headerName: "Price", width: 120 },
    { field: "qty", headerName: "Qty", width: 120 },
    { field: "money", headerName: "Money", width: 150 },
    { field: "breadth", headerName: "Breadth", width: 120 },
    { field: "in_qty", headerName: "In Qty", width: 120 },
    { field: "cmoney", headerName: "C Money", width: 150 },
    { field: "tax_rate", headerName: "Tax Rate", width: 120 },
    { field: "tax", headerName: "Tax", width: 120 },
    { field: "atax_rate", headerName: "Add Tax Rate", width: 120 },
    { field: "add_tax", headerName: "Add Tax", width: 120 },
    {
      field: "locked_information",
      headerName: "Locked Information",
      width: 120,
    },
    { field: "status", headerName: "Status", width: 120 },
  ],
  AC_CHG_A: [
    { field: "seq", headerName: "Seq", width: 100 },
    { field: "desc_item", headerName: "Description Item", width: 150 },
    { field: "desc_itemnm", headerName: "Description Item Name", width: 200 },
    { field: "ori", headerName: "Origin", width: 120 },
    { field: "addo", headerName: "Add O", width: 120 },
    {
      field: "locked_information",
      headerName: "Locked Information",
      width: 120,
    },
    { field: "status", headerName: "Status", width: 120 },
  ],
  AC_DESC_CHG: [
    { field: "seq", headerName: "Seq", width: 100 },
    { field: "desc_item", headerName: "Description Item", width: 150 },
    { field: "desc_itemnm", headerName: "Description Item Name", width: 200 },
    { field: "ori", headerName: "Origin", width: 120 },
    { field: "addo", headerName: "Add O", width: 120 },
    {
      field: "locked_information",
      headerName: "Locked Information",
      width: 120,
    },
    { field: "status", headerName: "Status", width: 120 },
  ],
  AC_PLAN_ORD: [
    { field: "se_id", headerName: "SE ID", width: 150 },
    { field: "se_seq", headerName: "SE Seq", width: 100 },
    { field: "pack_gu", headerName: "Pack GU", width: 120 },
    { field: "ship_seq", headerName: "Ship Seq", width: 120 },
    { field: "pay_cust", headerName: "Pay Customer", width: 150 },
    { field: "pay_cust_name", headerName: "Pay Cust Name", width: 200 },
    { field: "cust_no", headerName: "Cust No", width: 150 },
    { field: "prod_no", headerName: "Product No", width: 150 },
    { field: "prod_name", headerName: "Product Name", width: 200 },
    { field: "is_ship", headerName: "Is Ship", width: 100 },
  ],
  AC_PLAN_SIZE: [
    { field: "size_no", headerName: "Size no", width: 150 },
    { field: "pairs", headerName: "Pairs", width: 100 },
    { field: "price", headerName: "Price", width: 120 },
    { field: "money", headerName: "Money", width: 120 },
    { field: "prod_acno", headerName: "Prod Acno", width: 150 },
  ],
   AC_PLAN_PACK: [
    { field: "pk_seq", headerName: "PK Seq", width: 150 },
    { field: "sizerun", headerName: "Size Run", width: 100 },
    { field: "ctns_pairs", headerName: "CTNS Pairs", width: 120 },
    { field: "ctns", headerName: "CTNS", width: 120 },
    { field: "pairs", headerName: "Pairs", width: 150 },
  ],
  VW_ACREQ_D: [
    { field: "ord_date", headerName: "Order Date", width: 120 },
    { field: "order_no", headerName: "Order No", width: 150 },
    { field: "order_seq", headerName: "Order Seq", width: 100 },
    { field: "ac_send", headerName: "AC Send", width: 120 },
    { field: "sendnm", headerName: "Send Name", width: 180 },
    { field: "cont_no", headerName: "Cont No", width: 150 },
    { field: "ac_code", headerName: "AC Code", width: 150 },
    { field: "item_name", headerName: "Item Name", width: 200 },
    { field: "unit", headerName: "Unit", width: 100 },
    { field: "unitnm", headerName: "Unit Name", width: 150 },
    { field: "item_acno", headerName: "Item AC No", width: 150 },
    { field: "item_name1", headerName: "Item Name 1", width: 200 },
    { field: "unit1", headerName: "Unit 1", width: 100 },
    { field: "unitnm1", headerName: "Unit Name 1", width: 150 },
    { field: "ord_acqty", headerName: "Order AC Qty", width: 130 },
    { field: "req_acqty", headerName: "Request AC Qty", width: 130 },
    { field: "ac_no", headerName: "AC No", width: 120 },
    { field: "ac", headerName: "AC", width: 150 },
    { field: "chge_qty", headerName: "Change Qty", width: 120 },
    { field: "t_ac", headerName: "Total AC", width: 120 },
    { field: "t_rcpt", headerName: "Total Receipt", width: 120 },
    { field: "t_pass", headerName: "Total Pass", width: 120 },
    { field: "req_qc", headerName: "Request QC", width: 120 },
  ],
  AC_PROC_M: [
    { field: "ac_no", headerName: "Customs No", width: 150 },
    { field: "curr_name", headerName: "Currency Name", width: 130 },
    { field: "ac_date", headerName: "Customs Date", width: 120 },
    { field: "ac_chgs", headerName: "Customs No-S", width: 120 },
    { field: "ac_chgeno", headerName: "Customs Declaration No", width: 180 },
    { field: "ac_chgn", headerName: "Customs No-N", width: 120 },
    { field: "ac_chgo", headerName: "Customs No-O", width: 120 },
    { field: "col2", headerName: "Cancel Doc No", width: 150 },
    { field: "d_type_name", headerName: "Declaration Type", width: 150 },
    { field: "col1", headerName: "Seller Tax No", width: 150 },
    { field: "rec_person", headerName: "Seller Name", width: 200 },
    { field: "out_org", headerName: "Seller Address", width: 250 },
    { field: "ac_outer", headerName: "Export Address", width: 250 },
    { field: "rec_addr", headerName: "Delivery Address", width: 250 },
    { field: "js_no", headerName: "Tax Payment No", width: 150 },
    {
      field: "js_date",
      headerName: "Tax Payment Date",
      width: 140,
    },
    { field: "soso", headerName: "SOSO", width: 120 },
    { field: "ex_user", headerName: "License Handler", width: 150 },
    { field: "out_cont", headerName: "Export Contract No", width: 160 },
    { field: "out_date", headerName: "Export Date", width: 120 },
    {
      field: "out_vdate",
      headerName: "Export Contract Expiry",
      width: 160,
    },
    { field: "stoc_type", headerName: "Warehouse Type", width: 150 },
    { field: "in_cont", headerName: "Import Contract No", width: 160 },
    { field: "min_cont", headerName: "Annex", width: 120 },
    { field: "in_date", headerName: "Import Date", width: 120 },
    {
      field: "sta_date",
      headerName: "Contract Start Date",
      width: 150,
    },
    {
      field: "end_date",
      headerName: "Contract End Date",
      width: 150,
    },
    { field: "p_rec_person", headerName: "Contract Seller", width: 200 },
    { field: "outer", headerName: "Contract Seller Addr", width: 250 },
    { field: "in_curr", headerName: "Contract Currency", width: 140 },
    { field: "in_settle", headerName: "Contract Payment Term", width: 170 },
    { field: "in_set", headerName: "Import Payment Name", width: 170 },
    { field: "out_type", headerName: "Export Declaration Type", width: 180 },
    { field: "out_name", headerName: "Export Type Name", width: 160 },
    { field: "out_license", headerName: "Export License", width: 140 },
    { field: "in_type", headerName: "Import Declaration Type", width: 180 },
    { field: "intype_name", headerName: "Import Type Name", width: 160 },
    { field: "in_license", headerName: "Import License", width: 140 },
    { field: "com_invoice", headerName: "Commercial Invoice", width: 160 },
    {
      field: "com_date",
      headerName: "Commercial Inv Date",
      width: 150,
    },
    { field: "vat_invoice", headerName: "VAT Invoice", width: 150 },
    {
      field: "vat_date",
      headerName: "VAT Invoice Date",
      width: 140,
    },
    { field: "out_settle", headerName: "Export Payment Term", width: 170 },
    { field: "out_set", headerName: "Export Payment Name", width: 170 },
    { field: "sort", headerName: "Product Category", width: 150 },
    { field: "sort_name", headerName: "Category Name", width: 150 },
    { field: "out_curr", headerName: "Export Currency", width: 130 },
    {
      field: "out_crate",
      headerName: "Export Rate",
      width: 120,
    },
    { field: "in_curr", headerName: "Import Currency", width: 130 },
    {
      field: "in_crate",
      headerName: "Import Rate",
      width: 120,
    },
    {
      field: "sum_money",
      headerName: "Total Amount",
      width: 130,
    },
    { field: "tax", headerName: "Total Tax", width: 120 },
    { field: "peice", headerName: "Pieces", width: 100 },
    { field: "gross", headerName: "Gross Weight", width: 120 },
    { field: "grt_deptname", headerName: "Create Dept Name", width: 160 },
    { field: "grt_username", headerName: "Creator Name", width: 150 },
    { field: "last_username", headerName: "Modifier Name", width: 150 },
    {
      field: "locked_information",
      headerName: "Locked Information",
      width: 120,
    },
    { field: "status", headerName: "Status", width: 120 },
  ],
  AC_PROC_M_1: [
    { field: "ac_no", headerName: "Customs No", width: 150 },
    { field: "ac_date", headerName: "AC Date", width: 120 },
    { field: "ac_chgeno", headerName: "Customs Declaration No", width: 180 },
    { field: "vend_no", headerName: "Vendor No", width: 120 },
    { field: "vendnm", headerName: "Vendor Name", width: 200 },
    { field: "d_type_name", headerName: "D Type", width: 150 },
    { field: "stoc_type_name", headerName: "Stock Type", width: 150 },
    { field: "com_invoice", headerName: "COM Invoice", width: 150 },
    { field: "sta_date", headerName: "Start Date", width: 120 },
    { field: "end_date", headerName: "End Date", width: 120 },
    { field: "col2", headerName: "COL2", width: 100 },
    { field: "col1", headerName: "COL1", width: 100 },
    { field: "col4", headerName: "COL4", width: 100 },
    { field: "col6", headerName: "COL6", width: 120 },
    { field: "rec_person", headerName: "Rec Person", width: 120 },
    { field: "out_org", headerName: "Out Org", width: 120 },
    { field: "outer", headerName: "Outer", width: 100 },
    { field: "rec_addr", headerName: "Rec Address", width: 200 },
    { field: "js_no", headerName: "JS No", width: 120 },
    { field: "js_date", headerName: "JS Date", width: 120 },
    { field: "soso", headerName: "SOSO", width: 100 },
    { field: "in_cont", headerName: "In Cont", width: 120 },
    { field: "in_date", headerName: "In Date", width: 120 },
    { field: "sort", headerName: "Sort", width: 100 },
    { field: "sort_name", headerName: "Sort Name", width: 150 },
    { field: "in_curr", headerName: "Currency", width: 100 },
    { field: "curr_name", headerName: "Currency Name", width: 150 },
    { field: "in_crate", headerName: "In Rate", width: 120 },
    { field: "sum_money", headerName: "Sum Money", width: 150 },
    { field: "tax", headerName: "Tax", width: 120 },
    { field: "grt_deptname", headerName: "Dept Name", width: 150 },
    { field: "grt_username", headerName: "User Name", width: 150 },
    { field: "last_username", headerName: "Last User Name", width: 150 },
    { field: "locked_information", headerName: "Lock Information", width: 150 },
    { field: "status", headerName: "Status", width: 150 },
  ],
  AC_PROC_D: [
    { field: "seq", headerName: "Seq", width: 120 },
    { field: "ac_itemno", headerName: "AC ITEMNO", width: 150 },
    { field: "item_name", headerName: "Item Name", width: 100 },
    { field: "ac_send", headerName: "REF_PRICE", width: 120 },
    { field: "price", headerName: "PRICE", width: 180 },
    { field: "money", headerName: "MONEY", width: 150 },
    { field: "breadth", headerName: "BREADTH", width: 150 },
    { field: "ac_qty", headerName: "AC_QTY", width: 200 },
    { field: "unit", headerName: "Unit", width: 100 },
    { field: "unitnm", headerName: "Unit Name", width: 150 },
    { field: "rb_money", headerName: "RB MONEY", width: 150 },
    { field: "tax_rate", headerName: "TAX RATE", width: 200 },
    { field: "tax", headerName: "TAX", width: 100 },
    {
      field: "locked_information",
      headerName: "Locked Information",
      width: 120,
    },
    { field: "status", headerName: "Status", width: 150 },
  ],
  AC_PROC_D_1: [
    { field: "seq", headerName: "Seq", width: 80 },
    { field: "ac_itemno", headerName: "AC Item No", width: 150 },
    { field: "item_name", headerName: "Item Name", width: 200 },
    { field: "ac_item", headerName: "AC Item", width: 150 },
    { field: "ref_price", headerName: "Ref Price", width: 120 },
    { field: "money", headerName: "Money", width: 150 },
    { field: "ac_qty", headerName: "AC Qty", width: 120 },
    { field: "unit_name", headerName: "Unit Name", width: 150 },
    { field: "price", headerName: "Price", width: 120 },
    { field: "rb_money", headerName: "RB Money", width: 150 },
    { field: "tax_rate", headerName: "Tax Rate", width: 120 },
    { field: "tax", headerName: "Tax", width: 120 },
    { field: "in_crate", headerName: "In Rate", width: 120 },
    {
      field: "locked_information",
      headerName: "Locked Information",
      width: 180,
    },
    { field: "status", headerName: "Status", width: 100 },
  ],
  AC_DESC_PROC: [
    { field: "seq", headerName: "Seq", width: 100 },
    { field: "desc_item", headerName: "Description Item", width: 150 },
    { field: "desc_itemnm", headerName: "Description Item Name", width: 200 },
    { field: "ori", headerName: "Origin", width: 120 },
    { field: "addo", headerName: "Add O", width: 120 },
    {
      field: "locked_information",
      headerName: "Locked Information",
      width: 120,
    },
    { field: "status", headerName: "Status", width: 120 },
  ],
  VW_APDUE_ALL: [
    { field: "last_rcptdate", headerName: "Last Receipt Date", width: 150 },
    { field: "ap_refno", headerName: "AP Ref No", width: 150 },
    { field: "ap_refseq", headerName: "AP Ref Seq", width: 120 },
    { field: "item_acno", headerName: "Item AC No", width: 150 },
    { field: "rcpt_qty", headerName: "Receipt Qty", width: 120 },
    { field: "ac_qty", headerName: "AC Qty", width: 120 },
    { field: "ap_qty", headerName: "AP Qty", width: 120 },
    { field: "price", headerName: "Price", width: 120 },
    { field: "exchg_rate", headerName: "Exchange Rate", width: 130 },
    { field: "b_price", headerName: "B Price", width: 120 },
    { field: "ap_bmoney", headerName: "AP B Money", width: 130 },
    { field: "b_apmoney", headerName: "B AP Money", width: 130 },
  ],
  SE_SHIPING_M: [
    { field: "cust_id", headerName: "Cust ID", width: 120 },
    { field: "si_seq", headerName: "SI Seq", width: 100 },
    { field: "cust_no", headerName: "Cust No", width: 120 },
    { field: "cust_name", headerName: "Cust Name", width: 200 },
    { field: "cust_po", headerName: "Cust PO", width: 150 },
    { field: "start_date", headerName: "Start Date", width: 120 },
    { field: "end_date", headerName: "End Date", width: 120 },
    { field: "grt_deptname", headerName: "Dept Name", width: 150 },
    { field: "grt_username", headerName: "User Name", width: 150 },
    { field: "last_username", headerName: "Last User Name", width: 150 },
    { field: "locked_information", headerName: "Lock Information", width: 200 },
    { field: "status", headerName: "Status", width: 150 },
  ],
  SE_SHIPING_D: [
    { field: "si_type_name", headerName: "SI Type Name", width: 150 },
    { field: "bl_adress", headerName: "BL Address", width: 150 },
    { field: "nb_adress", headerName: "NB Address", width: 150 },
    { field: "two_nb", headerName: "Two NB", width: 100 },
    { field: "co", headerName: "CO", width: 100 },
    { field: "agent", headerName: "Agent Code", width: 120 },
    { field: "ag_name", headerName: "Agent Name", width: 200 },
    { field: "col1", headerName: "Country Code", width: 100 },
    { field: "countrynm", headerName: "Country Name", width: 150 },
    { field: "p_adress", headerName: "Destination Code", width: 120 },
    { field: "ad_name", headerName: "Destination Name", width: 200 },
    { field: "remark", headerName: "Remark", width: 200 },
    { field: "grt_deptname", headerName: "Dept Name", width: 150 },
    { field: "grt_username", headerName: "Grant User Name", width: 150 },
    { field: "last_username", headerName: "Last User Name", width: 150 },
    { field: "locked_information", headerName: "Lock Information", width: 200 },
    { field: "status", headerName: "Status", width: 150 },
  ],
  SE_PLAN_ORD: [
    { field: "se_seq", headerName: "SE Seq", width: 100 },
    { field: "pack_gu", headerName: "Pack GU", width: 100 },
    { field: "ship_seq", headerName: "Ship Seq", width: 100 },
    { field: "p_shipdate", headerName: "P Shipdate", width: 120 },
    { field: "p_shipqty", headerName: "P Shipqty", width: 120 },
    { field: "sum_ctns", headerName: "CTNS", width: 120 },
    { field: "cbm", headerName: "CBM", width: 100 },
    { field: "book_no", headerName: "Book No", width: 120 },
    { field: "etd", headerName: "ETD", width: 120 },
    { field: "invoice_no", headerName: "Invoice No", width: 150 },
    { field: "se_custid", headerName: "SE Custid", width: 120 },
    { field: "se_custname", headerName: "SE Custname", width: 200 },
    { field: "acc_custid", headerName: "ACC Custid", width: 120 },
    { field: "acc_custname", headerName: "ACC Custname", width: 200 },
    { field: "spec_code", headerName: "Spec Code", width: 150 },
    { field: "column1", headerName: "Column1", width: 120 },
    { field: "column1_name", headerName: "Column1 Name", width: 150 },
    { field: "send_type", headerName: "Send Type", width: 120 },
    { field: "send_typename", headerName: "Send Typename", width: 150 },
    { field: "ship_comp", headerName: "Ship Comp", width: 120 },
    { field: "ship_compname", headerName: "Ship Compname", width: 150 },
    { field: "col6", headerName: "Col6", width: 100 },
    { field: "col6_name", headerName: "Col6 Name", width: 150 },
    { field: "sendty", headerName: "Sendty", width: 120 },
    { field: "send_mode", headerName: "Send Mode", width: 120 },
    { field: "col5_name", headerName: "Col5 Name", width: 150 },
    { field: "col5", headerName: "Col5", width: 100 },
    { field: "col7", headerName: "Col7", width: 100 },
    { field: "p_exdate", headerName: "P Exdate", width: 120 },
    { field: "nlt", headerName: "NLT", width: 120 },
    { field: "nst", headerName: "NST", width: 120 },
    { field: "ex_status_name", headerName: "EX Status", width: 120 },
    { field: "sales_id", headerName: "Sales ID", width: 120 },
    { field: "packing_seid", headerName: "Packing SEID", width: 150 },
    { field: "so", headerName: "SO", width: 120 },
    { field: "grt_deptname", headerName: "GRT Deptname", width: 150 },
    { field: "grt_username", headerName: "GRT Username", width: 150 },
    { field: "last_username", headerName: "Last Username", width: 150 },
    {
      field: "locked_information",
      headerName: "Locked Information",
      width: 200,
    },
    { field: "status", headerName: "Status", width: 150 },
  ],
  SE_PLAN_SIZE: [
    { field: "pk_seq", headerName: "PK Seq", width: 100 },
    { field: "sizerun", headerName: "Sizerun", width: 120 },
    { field: "ctns_pairs", headerName: "CTNS Pairs", width: 120 },
    { field: "ctns", headerName: "CTNS", width: 120 },
    { field: "cbm", headerName: "CBM", width: 120 },
    { field: "pairs", headerName: "Pairs", width: 120 },
    { field: "grt_deptname", headerName: "GRT Deptname", width: 150 },
    { field: "grt_username", headerName: "GRT Username", width: 150 },
    { field: "last_username", headerName: "Last Username", width: 150 },
    {
      field: "locked_information",
      headerName: "Locked Information",
      width: 150,
    },
    { field: "status", headerName: "Status", width: 150 },
  ],
  SD_ORD_M_C: [
    { field: "so", headerName: "So", width: 100 },
    { field: "se_id", headerName: "SE_ID", width: 100 },
    { field: "se_custid", headerName: "Se Cust ID", width: 100 },
    { field: "se_seq", headerName: "SE_SEQ", width: 100 },
    { field: "pack_gu", headerName: "PACK_GU", width: 100 },
    { field: "cust_no", headerName: "CUST_NO", width: 100 },
    { field: "cust_nm", headerName: "CUSTNM", width: 100 },
    { field: "prod_no", headerName: "Prod no", width: 100 },
    { field: "se_qty", headerName: "SE_QTY", width: 100 },
    { field: "nlt", headerName: "NLT", width: 100 },
    { field: "po", headerName: "PO", width: 100 },
    { field: "mer_po", headerName: "MER_PO", width: 100 },
    { field: "se_day", headerName: "SE_DAY", width: 100 },
    { field: "available_qty", headerName: "Available Qty", width: 100 },
    { field: "status", headerName: "Status", width: 100 },
  ],
  VW_CONT_EXP: [
    { field: "cont_no", headerName: "cont_no", width: 120 },
    { field: "cont_category_name", headerName: "Category", width: 120 },
    { field: "issued_date", headerName: "issued_date", width: 120 },
    { field: "expire_date", headerName: "expire_date", width: 120 },
    { field: "last_edate", headerName: "last_edate", width: 120 },
    { field: "seller", headerName: "seller", width: 120 },
    { field: "buyer", headerName: "buyer", width: 125 },
    { field: "sum_money", headerName: "sum_money", width: 130 },
    { field: "currency", headerName: "currency", width: 120 },
    { field: "currencynm", headerName: "currency_name", width: 120 },
    { field: "locked_information", headerName: "Lock Information", width: 120 },
    { field: "status", headerName: "status", width: 150 },
  ],
  VW_CHG_EXMP: [
    { field: "seq", headerName: "Seq", width: 140 },
    { field: "min_cont", headerName: "Min Cont", width: 140 },
    { field: "out_date", headerName: "Out Date", width: 140 },
    { field: "ac_chgno", headerName: "AC Chgno", width: 140 },
    { field: "ac_no", headerName: "AC No", width: 130 },
    { field: "ac_itemno", headerName: "AC Item No", width: 130 },
    { field: "ac_itemname", headerName: "AC Item Name", width: 130 },
    { field: "unit", headerName: "Unit", width: 130 },
    { field: "unit_name", headerName: "Unit name", width: 130 },
    { field: "qty", headerName: "Qty", width: 140 },
    { field: "money", headerName: "Money", width: 130 },
  ],
  VW_CHG_EXP: [
    { field: "ac_no", headerName: "AC No", width: 120 },
    { field: "ac_type_name", headerName: "AC Type", width: 130 },
    { field: "out_date", headerName: "Out Date", width: 120 },
    { field: "d_type_name", headerName: "D Type", width: 100 },
    { field: "ac_chgs", headerName: "AC Chgs", width: 100 },
    { field: "ac_chgno", headerName: "AC Chgno", width: 120 },
    { field: "ac_chgn", headerName: "AC Chgn", width: 100 },
    { field: "ac_chgo", headerName: "AC Chgo", width: 100 },
    { field: "cont_no", headerName: "Cont No", width: 120 },
    { field: "min_cont", headerName: "Min Cont", width: 100 },
    { field: "ac_addr", headerName: "AC Addr", width: 150 },
    { field: "issued_date", headerName: "Issued Date", width: 120 },
    { field: "expire_date", headerName: "Expire Date", width: 120 },
    { field: "old_no", headerName: "Old No", width: 120 },
    { field: "org_tax", headerName: "Org Tax", width: 120 },
    { field: "ac_bom", headerName: "AC Bom", width: 100 },
    { field: "org_addr", headerName: "Org Addr", width: 150 },
    { field: "cust_tax", headerName: "Cust Tax", width: 120 },
    { field: "ac_row", headerName: "AC Row", width: 100 },
    { field: "cust_addr", headerName: "Cust Addr", width: 150 },
    { field: "rec_addr", headerName: "Rec Addr", width: 150 },
    { field: "sort", headerName: "Sort", width: 80 },
    { field: "sort_name", headerName: "Sort Name", width: 120 },
    { field: "agent_make", headerName: "Agent Make", width: 120 },
    { field: "chg_type", headerName: "Chg Type", width: 100 },
    { field: "typenm", headerName: "Type Name", width: 120 },
    { field: "license", headerName: "License", width: 120 },
    { field: "lic_date", headerName: "Lic Date", width: 120 },
    { field: "pass_date", headerName: "Pass Date", width: 120 },
    { field: "out_port", headerName: "Out Port", width: 100 },
    { field: "port_name", headerName: "Port Name", width: 120 },
    { field: "in_country", headerName: "In Country", width: 100 },
    { field: "trade", headerName: "Trade", width: 100 },
    { field: "trade_name", headerName: "Trade Name", width: 120 },
    { field: "payment", headerName: "Payment", width: 100 },
    { field: "pay_name", headerName: "Pay Name", width: 120 },
    { field: "curr_no", headerName: "Curr No", width: 100 },
    { field: "curr_name", headerName: "Curr Name", width: 120 },
    { field: "curr_rate", headerName: "Curr Rate", width: 100 },
    { field: "gross", headerName: "Gross", width: 100 },
    { field: "peice", headerName: "Peice", width: 100 },
    { field: "grt_dept", headerName: "Grt Dept", width: 100 },
    { field: "grt_deptname", headerName: "Grt Deptname", width: 150 },
    { field: "grt_username", headerName: "Grt Username", width: 120 },
    { field: "last_username", headerName: "Last Username", width: 120 },
    { field: "v_ac_chgno", headerName: "V AC Chgno", width: 120 },
    { field: "v_cont_no", headerName: "V Cont No", width: 120 },
    { field: "v_out_date", headerName: "V Out Date", width: 120 },
    { field: "v_min_cont", headerName: "V Min Cont", width: 120 },
    { field: "v_curr_no", headerName: "V Curr No", width: 100 },
    { field: "currnm", headerName: "Currency", width: 120 },
    { field: "sum_qty", headerName: "Sum Qty", width: 100 },
    { field: "sum_money", headerName: "Sum Money", width: 120 },
    { field: "tax", headerName: "Tax", width: 100 },
    { field: "se_id", headerName: "SE ID", width: 100 },
    { field: "ship_seq", headerName: "Ship Seq", width: 100 },
    { field: "locked_information", headerName: "Locked", width: 100 },
    { field: "status", headerName: "Status Name", width: 150 },
  ],
  SE_PAY: [
    { field: "pay_no", headerName: "Pay No", width: 200 },
    { field: "name_t", headerName: "Name (Traditional)", width: 200 },
    { field: "name_e", headerName: "Name (English)", width: 200 },
    { field: "name_s", headerName: "Name (Simplified)", width: 200 },
    { field: "dt_pct", headerName: "DT PCT", width: 220 },
    { field: "cal_days", headerName: "Cal Days", width: 220 },
    { field: "note", headerName: "Note", width: 250 },
    {
      field: "locked_information",
      headerName: "Locked Information",
      width: 150,
    },
    { field: "status", headerName: "Status", width: 240 },
  ],
  SD_ORD_M: [
    { field: "se_id", headerName: "SE ID", width: 150 },
    { field: "se_day", headerName: "SE Day", width: 120 },
    { field: "se_ver", headerName: "Version", width: 100 },
    { field: "mer_po", headerName: "MER PO", width: 150 },
    { field: "s_custno", headerName: "Seller Customer No", width: 150 },
    { field: "se_custidnm", headerName: "Seller Name", width: 200 },
    { field: "a_custno", headerName: "Account Customer No", width: 150 },
    { field: "acc_custnm", headerName: "Account Name", width: 200 },
    { field: "paynm", headerName: "Payment", width: 150 },
    { field: "last_usernm", headerName: "Last User Name", width: 150 },
    { field: "grt_deptnm", headerName: "Department Name", width: 200 },
    { field: "grt_usernm", headerName: "Approve User Name", width: 150 },
    { field: "status", headerName: "Status", width: 150 },
  ],
  SD_PRICE_ITEM: [
    { field: "se_seq", headerName: "Sequence", width: 150 },
    { field: "prod_no", headerName: "Product No", width: 150 },
    { field: "prodnm", headerName: "Product Name", width: 250 },
    { field: "nst", headerName: "NST", width: 120 },
    { field: "nlt", headerName: "NLT", width: 150 },
    { field: "se_qty", headerName: "Quantity", width: 120 },
    { field: "curr_name", headerName: "Currency", width: 120 },
    { field: "std_price", headerName: "Standard Price", width: 130 },
    { field: "adj_price", headerName: "Adjust Price", width: 130 },
    { field: "se_price", headerName: "SE Price", width: 120 },
    { field: "se_money", headerName: "SE Money", width: 130 },
    { field: "last_usernm", headerName: "Last User Name", width: 150 },
    { field: "grt_deptnm", headerName: "Department Name", width: 200 },
    { field: "grt_usernm", headerName: "Approve User Name", width: 150 },
    { field: "status", headerName: "Status", width: 150 },
  ],
  PLAN_ORD: [
    { field: "se_id", headerName: "SE ID", width: 150 },
    { field: "se_seq", headerName: "Sequence", width: 100 },
    { field: "pack_gu", headerName: "Pack GU", width: 100 },
    { field: "ship_seq", headerName: "Ship Seq", width: 100 },
    { field: "p_shipdate", headerName: "Ship Date", width: 130 },
    { field: "p_shipqty", headerName: "Ship Qty", width: 120 },
    { field: "po", headerName: "PO", width: 150 },
    { field: "prod_no", headerName: "Product No", width: 150 },
    { field: "cust_no", headerName: "Customer No", width: 150 },
    { field: "custnm", headerName: "Customer Name", width: 200 },
    { field: "prod_name", headerName: "Product Name", width: 250 },
    { field: "color", headerName: "Color", width: 150 },
    { field: "ex_status", headerName: "Export Status", width: 150 },
  ],
  SE_INV_M: [
    { field: "invoice_id", headerName: "Invoice ID", width: 150 },
    { field: "invoice_no", headerName: "Invoice No", width: 150 },
    { field: "ac_no", headerName: "AC No", width: 150 },
    { field: "invoice_date", headerName: "Invoice Date", width: 130 },
    { field: "fcr_date", headerName: "FCR Date", width: 130 },
    { field: "cdc_no", headerName: "CDC No", width: 130 },
    { field: "cdc_date", headerName: "CDC Date", width: 130 },
    { field: "hs_code", headerName: "HS Code", width: 130 },
    { field: "sailing_date", headerName: "Sailing Date", width: 130 },
    { field: "per", headerName: "PER", width: 100 },
    { field: "exp_port", headerName: "Export Port", width: 120 },
    { field: "exp_name", headerName: "Export Port Name", width: 180 },
    { field: "dest_port", headerName: "Dest Port", width: 120 },
    { field: "dest_name", headerName: "Dest Port Name", width: 180 },
    { field: "sort", headerName: "Sort", width: 100 },
    { field: "sort_name", headerName: "Sort Name", width: 150 },
    { field: "nw", headerName: "NW", width: 100 },
    { field: "gw", headerName: "GW", width: 100 },
    { field: "submission_date", headerName: "Submission Date", width: 130 },
    { field: "shipment_no", headerName: "Shipment No", width: 150 },
    { field: "via", headerName: "Via", width: 100 },
    { field: "trade", headerName: "Trade", width: 100 },
    { field: "trade_name", headerName: "Trade Name", width: 150 },
    { field: "payment", headerName: "Payment", width: 120 },
    { field: "payment_name", headerName: "Payment Name", width: 150 },
    { field: "bank_name", headerName: "Bank Name", width: 180 },
    { field: "account_addr", headerName: "Account Address", width: 200 },
    { field: "goods_desc", headerName: "Goods Desc", width: 200 },
    { field: "locked_information", headerName: "Locked", width: 100 },
    { field: "status_name", headerName: "Status Name", width: 150 },
  ],
  CHG_M: [
    { field: "ac_no", headerName: "AC No", width: 150 },
    { field: "ac_chgno", headerName: "AC CHG No", width: 150 },
    { field: "out_date", headerName: "Out Date", width: 130 },
    { field: "cont_no", headerName: "Cont No", width: 150 },
    { field: "curr_no", headerName: "Currency", width: 100 },
    { field: "curr_name", headerName: "Currency Name", width: 150 },
    { field: "sum_qty", headerName: "Sum Qty", width: 120 },
    { field: "sum_money", headerName: "Sum Money", width: 130 },
    { field: "tax", headerName: "Tax", width: 100 },
    { field: "status", headerName: "Status", width: 80 },
    { field: "status_name", headerName: "Status Name", width: 150 },
    { field: "chg_type", headerName: "CHG Type", width: 100 },
    { field: "chg_type_name", headerName: "CHG Type Name", width: 150 },
  ],
  SE_INV_D: [
    { field: "ship_seq", headerName: "Ship Seq", width: 100 },
    { field: "pk_seq", headerName: "PK Seq", width: 100 },
    { field: "size_run", headerName: "Size Run", width: 120 },
    { field: "ctn_pairs", headerName: "CTN Pairs", width: 120 },
    { field: "ctns", headerName: "CTNS", width: 100 },
    { field: "s_no", headerName: "S No", width: 100 },
    { field: "e_no", headerName: "E No", width: 125 },
    { field: "length", headerName: "Length", width: 120 },
    { field: "width", headerName: "Width", width: 120 },
    { field: "high", headerName: "High", width: 120 },
    { field: "cbm", headerName: "CBM", width: 120 },
    { field: "net_weight", headerName: "Net Weight", width: 120 },
    { field: "gross_weight", headerName: "Gross Weight", width: 120 },
  ],
  SD_PRICE_ITEM_1: [
    { field: "se_id", headerName: "SE ID", width: 150 },
    { field: "se_seq", headerName: "SE Seq", width: 150 },
    { field: "prod_no", headerName: "Product No", width: 150 },
    { field: "curr_no", headerName: "Currency", width: 120 },
    { field: "curr_name", headerName: "Currency Name", width: 150 },
    { field: "adj_price", headerName: "Adj Price", width: 120 },
    { field: "se_qty", headerName: "SE Qty", width: 125 },
    { field: "se_money", headerName: "SE Money", width: 130 },
    { field: "total_nw", headerName: "Total NW", width: 130 },
    { field: "total_ctns", headerName: "Total CTNS", width: 130 },
    { field: "total_gw", headerName: "Total GW", width: 130 },
  ],
  PAKING_LIST_M: [
    { field: "se_id", headerName: "SE ID", width: 130 },
    { field: "se_seq", headerName: "SE Seq", width: 100 },
    { field: "pack_gu", headerName: "Pack GU", width: 100 },
    { field: "ship_seq", headerName: "Ship Seq", width: 100 },
    { field: "invoice_no", headerName: "Invoice No", width: 150 },
    { field: "transportation", headerName: "Transportation", width: 130 },
    { field: "cust_no", headerName: "Cust No", width: 120 },
    { field: "cust_on", headerName: "Cust On", width: 120 },
    { field: "po_no", headerName: "PO No", width: 120 },
    { field: "art_no", headerName: "Art No", width: 120 },
    { field: "art_name", headerName: "Art Name", width: 150 },
    { field: "made_out", headerName: "Made Out", width: 120 },
    { field: "made_to", headerName: "Made To", width: 120 },
    { field: "fcr_date", headerName: "FCR Date", width: 120 },
    { field: "hs_code", headerName: "HS Code", width: 120 },
    { field: "com_name", headerName: "Com Name", width: 150 },
    { field: "com_add", headerName: "Com Address", width: 200 },
  ],
  PAKING_LIST_D: [
    { field: "c_no", headerName: "C No", width: 130 },
    { field: "size_no", headerName: "Size No", width: 130 },
    { field: "cr_size", headerName: "CR Size", width: 130 },
    { field: "ctns_pairs", headerName: "CTNS Pairs", width: 130 },
    { field: "ctns", headerName: "CTNS", width: 120 },
    { field: "nw", headerName: "Net Weight", width: 120 },
    { field: "gw", headerName: "Gross Weight", width: 120 },
    { field: "ship_qty", headerName: "Ship Qty", width: 120 },
    { field: "t_nw_show", headerName: "Total NW", width: 120 },
    { field: "t_gw_show", headerName: "Total GW", width: 120 },
    { field: "measure_show", headerName: "Measure", width: 120 },
    { field: "cbm_show", headerName: "CBM", width: 120 },
  ],

  AC_ISSUE_M_T: [
    { field: "conf_seq", headerName: "Conf Seq", width: 150 },
    { field: "chg_no", headerName: "CHG No", width: 150 },
    { field: "cont_no", headerName: "Cont No", width: 150 },
    { field: "ac_date", headerName: "AC Date", width: 120 },
    { field: "ac_typename", headerName: "AC Type", width: 130 },
    { field: "year_no", headerName: "Year No", width: 100 },
    { field: "conf_date", headerName: "Conf Date", width: 120 },
    { field: "acbom_no", headerName: "ACBOM No", width: 130 },
    { field: "issue_seq", headerName: "Issue Seq", width: 150 },
    { field: "chgs_col3", headerName: "CHGS/Year Seq", width: 150 },
    { field: "old_no", headerName: "Old No", width: 130 },
    { field: "out_dtype", headerName: "Out D Type", width: 110 },
    { field: "col4", headerName: "Issue Date", width: 120 },
    { field: "col2", headerName: "Void Doc No", width: 130 },
    { field: "money", headerName: "Money", width: 120 },
    { field: "percent", headerName: "%", width: 80 },
    { field: "lock_seq", headerName: "Lock Seq", width: 100 },
    {
      field: "locked_information",
      headerName: "Locked Information",
      width: 100,
    },
    { field: "status", headerName: "Status", width: 130 },
  ],
  VW_AC_ISSUE_T: [
    { field: "matd_no", headerName: "Material No", width: 150 },
    { field: "ac_itemname", headerName: "Item Name", width: 200 },
    { field: "unit_name", headerName: "Unit", width: 100 },
    { field: "left_qty", headerName: "Left Qty", width: 120 },
    { field: "left_issue", headerName: "Left Issue", width: 120 },
    { field: "req_qty", headerName: "Req Qty", width: 120 },
    { field: "issue_qty", headerName: "Issue Qty", width: 120 },
  ],
  AC_ISSUE_MATD_T: [
    { field: "prod_no", headerName: "Prod No", width: 150 },
    { field: "prod_name", headerName: "Prod Name", width: 200 },
    { field: "req_issue", headerName: "Req Issue", width: 100 },
    { field: "unit_qty", headerName: "Unit Qty", width: 120 },
    { field: "req_qty", headerName: "Req Qty", width: 120 },
    { field: "issue_qty", headerName: "Issue Qty", width: 120 },
    { field: "remark", headerName: "Remark", width: 200 },
    {
      field: "locked_information",
      headerName: "Lock Information",
      width: 160,
    },
    { field: "status", headerName: "status", width: 160 },
  ],
  AC_CHK_T: [
    { field: "issue_seq", headerName: "Issue Seq", width: 120 },
    { field: "src", headerName: "Source", width: 150 },
    { field: "in_acno", headerName: "In AC No", width: 150 },
    { field: "in_chg", headerName: "In CHG", width: 200 },
    { field: "d_type", headerName: "D Type", width: 150 },
    { field: "qty", headerName: "Qty", width: 100 },
    { field: "pairs", headerName: "Pairs", width: 100 },
    { field: "price", headerName: "Price", width: 120 },
    {
      field: "locked_information",
      headerName: "Lock Information",
      width: 160,
    },
    { field: "status", headerName: "status", width: 160 },
  ],
  VW_AC_SUM: [
    { field: "ac_itemno", headerName: "AC Item No", width: 250 },
    { field: "ac_itemname", headerName: "AC Item Name", width: 250 },
    { field: "in_qty", headerName: "In Qty", width: 250 },
    { field: "out_qty", headerName: "Out Qty", width: 250 },
    { field: "left_qty", headerName: "Left Qty", width: 250 },
    { field: "stoc_type", headerName: "Stoc Type", width: 230 },
  ],
  VW_AC_CHGSUM: [
    { field: "ac_no", headerName: "AC No", width: 120 },
    { field: "ac_chgno", headerName: "AC CHG No", width: 100 },
    { field: "ac_date", headerName: "AC Date", width: 100 },
    { field: "cont_no", headerName: "Cont No", width: 120 },
    { field: "ac_itemno", headerName: "AC Item No", width: 120 },
    { field: "ac_itemname", headerName: "AC Item Name", width: 120 },
    { field: "qty", headerName: "Qty", width: 105 },
    { field: "over_qty", headerName: "Over Qty", width: 100 },
    { field: "d_type", headerName: "D Type", width: 120 },
    { field: "stoc_type", headerName: "Stoc Type", width: 120 },
    { field: "com_invoice", headerName: "Com Invoice", width: 120 },
    { field: "fact_date", headerName: "Fact Date", width: 120 },
    { field: "status", headerName: "Status", width: 120 },
  ],
  VW_AC_CHK_T: [
    { field: "in_acseq", headerName: "In AC Seq", width: 150 },
    { field: "bom_seq", headerName: "BOM Seq", width: 150 },
    { field: "out_acno", headerName: "Out AC No", width: 150 },
    { field: "out_chgno", headerName: "Out CHG No", width: 150 },
    { field: "out_date", headerName: "Out Date", width: 120 },
    { field: "prod_no", headerName: "Prod No", width: 150 },
    { field: "ac_itemname", headerName: "AC Item Name", width: 250 },
    { field: "unit_qty", headerName: "Unit Qty", width: 100 },
    { field: "loss_per", headerName: "Loss Per", width: 100 },
    { field: "pairs", headerName: "Pairs", width: 100 },
    { field: "qty", headerName: "Qty", width: 100 },
    { field: "over_qty", headerName: "Over Qty", width: 100 },
  ],
  SE_SALES: [
    { field: "shipping_order", headerName: "Shipping Order", width: 150 },
    { field: "sales_date", headerName: "Sales Date", width: 120 },
    { field: "send_type", headerName: "Send Type", width: 100 },
    { field: "send_typename", headerName: "Send Type Name", width: 150 },
    { field: "send_corp", headerName: "Send Corp", width: 120 },
    { field: "send_compname", headerName: "Send Comp Name", width: 180 },
    { field: "destination", headerName: "Destination", width: 150 },
    { field: "remark", headerName: "Remark", width: 200 },
    { field: "grt_deptname", headerName: "Dept Name", width: 150 },
    { field: "grt_username", headerName: "Grt User Name", width: 150 },
    { field: "last_username", headerName: "Last User Name", width: 150 },
    { field: "status", headerName: "Status", width: 130 },
  ],
  SE_SALES_D: [
    { field: "seq", headerName: "SEQ", width: 150 },
    { field: "sales_seq", headerName: "Sales Seq", width: 150 },
    { field: "se_id", headerName: "SE ID", width: 150 },
    { field: "se_seq", headerName: "SE Seq", width: 150 },
    { field: "ac_no", headerName: "Ac No", width: 150 },
    { field: "ac_name", headerName: "Ac Name", width: 150 },
    { field: "ship_seq", headerName: "Ship Seq", width: 150 },
    { field: "prod_no", headerName: "Prod No", width: 150 },
    { field: "container_vehicle", headerName: "Container/Vehicle", width: 150 },
    { field: "book_no", headerName: "Book No", width: 150 },
    { field: "invoice_no", headerName: "Invoice No", width: 140 },
    { field: "pairs", headerName: "Pairs", width: 145 },
  ],
  AC_EXPECT_M: [
    { field: "expect_id", headerName: "Expect Id ", width: 80 },
    { field: "type_name", headerName: "Type", width: 100 },
    { field: "s_date1", headerName: "Sdate 1", width: 120 },
    { field: "e_date1", headerName: "Edate 1", width: 100 },
    { field: "s_date2", headerName: "Sdate 2", width: 100 },
    { field: "e_date2", headerName: "Edate 2", width: 150 },
    { field: "grt_deptname", headerName: "Department Name", width: 150 },
    { field: "grt_username", headerName: "Create User Name", width: 120 },
    { field: "last_username", headerName: "Last User Name", width: 150 },
    {
      field: "locked_information",
      headerName: "Lock Information",
      width: 160,
    },
    { field: "status", headerName: "Status", width: 100 },
  ],
  AC_EXPECT_SE: [
    { field: "bom_prod", headerName: "Bom Prod ", width: 200 },
    { field: "prod_no", headerName: "Prod No", width: 200 },
    { field: "prod_name", headerName: "Prod Name", width: 175 },
    { field: "se_qty", headerName: "Se Qty", width: 170 },
    { field: "ac_shoe", headerName: "Ac Shoe", width: 170 },
  ],
  AC_EXPECT_MATD: [
    { field: "matd_no", headerName: "Bom Prod ", width: 200 },
    { field: "matd_name", headerName: "Prod No", width: 200 },
    { field: "matd_unit", headerName: "Prod Name", width: 175 },
    { field: "loss_per", headerName: "Se Qty", width: 170 },
    { field: "expect_qty", headerName: "Ac Shoe", width: 170 },
    { field: "left_qty", headerName: "Left Qty", width: 170 },
  ],
  AC_CO_M: [
    { field: "co_id", headerName: "Co Id", width: 150 },
    { field: "se_id", headerName: "Se Id", width: 150 },
    { field: "se_seq", headerName: "Se Seq", width: 100 },
    { field: "pack_gu", headerName: "Pack Gu", width: 100 },
    { field: "ship_seq", headerName: "Ship Seq", width: 100 },
    { field: "board_date", headerName: "Board Date", width: 130 },
    { field: "bl_no", headerName: "Bl No", width: 150 },
    { field: "sort_name", headerName: "Sort", width: 130 },
    { field: "print_id", headerName: "Print Id", width: 120 },
    { field: "co_no", headerName: "Co No", width: 150 },
    { field: "el_no", headerName: "El No", width: 130 },
    { field: "el_country", headerName: "El Country", width: 150 },
    { field: "ar_no", headerName: "Ar No", width: 130 },
    { field: "ws_no", headerName: "Ws No", width: 130 },
    { field: "ql_date", headerName: "Ql Date", width: 130 },
    { field: "invoice_no", headerName: "Invoice No", width: 160 },
    { field: "ship_order", headerName: "Ship Order", width: 130 },
    { field: "mer_po", headerName: "Mer Po", width: 130 },
    { field: "po", headerName: "Po", width: 130 },
    { field: "dest_name", headerName: "Destination", width: 150 },
    { field: "boat_companynm", headerName: "Boat Company", width: 160 },
    { field: "boat_name", headerName: "Boat Name", width: 150 },
    { field: "fa_cbm", headerName: "Fa Cbm", width: 120 },
    { field: "net_weight", headerName: "Net Weight", width: 120 },
    { field: "gross", headerName: "Gross", width: 120 },
    { field: "note", headerName: "Note", width: 200 },
    { field: "is_prt", headerName: "Is Prt", width: 100 },
    { field: "grt_deptname", headerName: "Dept Name", width: 160 },
    { field: "grt_username", headerName: "Grt Username", width: 150 },
    { field: "last_username", headerName: "Last Username", width: 150 },
    {
      field: "locked_information",
      headerName: "Locked Information",
      width: 150,
    },
    { field: "status", headerName: "Status", width: 150 },
  ],
  SE_PLAN_ORD_LINK: [
    { field: "se_id", headerName: "SE ID", width: 120 },
    { field: "se_ver", headerName: "SE Ver", width: 80 },
    { field: "se_seq", headerName: "SE Seq", width: 80 },
    { field: "pack_gu", headerName: "Pack GU", width: 100 },
    { field: "ship_seq", headerName: "Ship Seq", width: 90 },
    { field: "ac_no", headerName: "AC No", width: 130 },
    { field: "ac_chgs", headerName: "AC CHGS", width: 130 },
    { field: "cust_no", headerName: "Cust No", width: 120 },
    { field: "cust_name", headerName: "Cust Name", width: 160 },
    { field: "po", headerName: "PO", width: 130 },
    { field: "prod_no", headerName: "Prod No", width: 130 },
    { field: "spg_no", headerName: "SPG No", width: 120 },
    { field: "prod_name", headerName: "Prod Name", width: 160 },
    { field: "p_shipqty", headerName: "Ship Qty", width: 100 },
    { field: "p_shipdate", headerName: "Ship Date", width: 120 },
    { field: "sel", headerName: "SEL", width: 80 },
  ],
  SAP_TRANS_TYPE: [
    { field: "type_no", headerName: "Type No", width: 260 },
    { field: "type_name", headerName: "Type Name", width: 260 },
    { field: "material_out", headerName: "Material Out", width: 260 },
  ],
  RD_TEMP: [
    { field: "item_no", headerName: "Item No", width: 450 },
    { field: "code_no", headerName: "Code No", width: 443 },
  ],
  TEXT_IMPORT: [
    { field: "varchar03", headerName: "Varchar 03", width: 260 },
    { field: "varchar04", headerName: "varchar 04", width: 260 },
    { field: "varchar05", headerName: "varchar 05", width: 260 },
  ],
};
export const getTableColumns = (tableName, getHeaderName) => {
  const structure = TableColumnsStructure[tableName];
  if (!structure) return [];

  return structure.map((col) => ({
    ...col,
    headerName: getHeaderName(tableName, col.field),
  }));
};
export default TableColumns;
