const FULL_WIDTH_TABLES = new Set([
  "FACTORY",
  "USER_PERMISSION",
  "BASIC_DATA",
  "BASIC_DATA_CATEGORY",
  "AC_IMP_MATERIAL_TRACKING",
  "AC_ITEM_M",
  "AC_ITEM_REF",
  "AC_SHOE_M",
  "AC_SHOE_REF",
  "AC_BOM_M",
  "AC_PROD_M",
  "PROGRAM",
  "RD_SIZE_D",
  "VW_AC_SHOEBOM",
  "AC_VEND_BASE",
  "AC_SEND_BASE",
  "AC_REQ_M",
  "AC_REQ_ORDER",
  "IV_TRANS_D_TW",
  "VW_AC_ALLCHK",
  "AC_SRCORDER_M",
  "VW_CONT_IMP",
  "AC_CONT_D",
  "VW_CONT_USE",
  "VW_CONT_IMP_1",
  "AC_INM_M",
  "AC_INM_D",
  "VW_CHG_M",
  "AC_CHG_D",
  "AC_CHG_A",
  "VW_ACREQ_D",
  "AC_PROC_M",
  "AC_PROC_D",
  "AC_DESC_PROC",
  "AC_PROC_M_1",
  "AC_PROC_D_1",
  "SE_SHIPING_M",
  "SE_SHIPING_D",
  "VW_APDUE_ALL",
  "SE_PLAN_ORD",
  "SE_PLAN_SIZE",
  "SD_ORD_M_C",
  "VW_CONT_EXP",
  "VW_CHG_EXMP",
  "SE_PAY",
  "SD_ORD_M",
  "SD_PRICE_ITEM",
  "VW_CHG_EXP",
  "PLAN_ORD",
  "SE_INV_M",
  "CHG_M",
  "SE_INV_D",
  "SD_PRICE_ITEM_1",
  "PAKING_LIST_M",
  "PAKING_LIST_D",
  "AC_ISSUE_M_T",
  "AC_ISSUE_MATD_T",
  "VW_AC_ISSUE_T",
  "AC_CHK_T",
  "VW_AC_SUM",
  "VW_AC_CHGSUM",
  "VW_AC_CHK_T",
  "SE_SALES",
  "SE_SALES_D",
  "AC_EXPECT_M",
  "AC_EXPECT_SE",
  "AC_EXPECT_MATD",
  "AC_CO_M",
  "SE_PLAN_ORD_LINK",
  "SAP_TRANS_TYPE",
  "RD_TEMP",
  "TEXT_IMPORT",
  "AC_DESC_CHG",
  "AC_PLAN_ORD",
  "AC_PLAN_SIZE",
  "AC_PLAN_PACK",
]);

const ZERO_MIN_HEIGHT_TABLES = new Set([
  "BASIC_DATA_CATEGORY",
  "AC_ITEM_M",
  "AC_SHOE_M",
  "AC_PROD_M",
  "AC_BOM_M",
  "USER_PERMISSION_DEPARTMENT",
]);

const FOOTER_FLEX = {
  AC_SHOE_M: 1,
  AC_SHOE_REF: 2.2,
  USER: 0.8,
  AC_PROD_M: 0.7,
  DEPARTMENTS: 0.7,
  PROGRAM_FIELD_TITLE: 0.7,
  USER_PERMISSION: 0.75,
  USER_PERMISSION_DEPARTMENT: 0.75,
  BASIC_DATA_CATEGORY: 0.6,
  BASIC_DATA: 0.6,
  AC_ITEM_M: 0.6,
  AC_ITEM_REF: 0.6,
  AC_REQ_ORDER: 0.6,
  AC_CHG_A: 2.2,
  AC_DESC_CHG: 2.2,
  AC_PLAN_ORD: 2.2,
  AC_PLAN_SIZE: 2.2,
  AC_PLAN_PACK: 2.2,
  AC_ISSUE_MATD_T: 2.2,
  AC_CHK_T: 2.2,
  IV_TRANS_D_TW: 2.2,
  AC_DESC_PROC: 2.2,
  VW_APDUE_ALL: 2.2,
  VW_ACREQ_D: 2.2,
  AC_EXPECT_MATD: 2.2,
  RD_TEMP: 2.3,
  SAP_TRANS_TYPE: 2.3,
  TEXT_IMPORT: 2.3,
};

const FOOTER_FLEX_ONE_TABLES = new Set([
  "RD_SIZE_D",
  "VW_CHG_M",
  "AC_EXPECT_M",
  "AC_ISSUE_M_T",
  "VW_AC_ISSUE_T",
  "VW_CHG_EXP",
  "AC_PROC_M",
  "AC_PROC_M_1",
  "AC_PROC_D",
  "AC_PROC_D_1",
  "AC_CHG_D",
  "AC_EXPECT_SE",
]);

export const getMainTableGridSize = (tableName) => {
  if (tableName === "USER") return 8;
  if (tableName === "VW_AC_SRCORDER") return 20;
  return FULL_WIDTH_TABLES.has(tableName) ? 12 : 10;
};

export const getTableContainerMinHeight = (tableName, tableHeight) =>
  ZERO_MIN_HEIGHT_TABLES.has(tableName) ? 0 : tableHeight;

export const getFooterPaginationFlex = (tableName) => {
  if (FOOTER_FLEX_ONE_TABLES.has(tableName)) return 1;
  return FOOTER_FLEX[tableName] ?? 0.6;
};

export const getSidePanelMaxHeight = ({
  title,
  tableHeight,
  fallback = "calc(100vh - 350px)",
}) => (title === "USER_PERMISSION" ? 500 : tableHeight || fallback);
