const Joi = require("joi");

const createAcCoMSchema = Joi.object({
  factory_code:       Joi.string().max(30).required(),
  co_id:              Joi.number().integer().required(),
  cust_id:            Joi.string().max(30).allow(null, "").default(null).optional(),
  sales_id:           Joi.number().integer().allow(null).default(null).optional(),
  sales_no:           Joi.string().max(30).allow(null, "").default(null).optional(),
  sales_seq:          Joi.number().precision(2).allow(null).default(null).optional(),
  se_id:              Joi.string().max(30).allow(null, "").default(null).optional(),
  se_seq:             Joi.number().precision(2).allow(null).default(null).optional(),
  ship_seq:           Joi.number().precision(2).allow(null).default(null).optional(),
  mer_po:             Joi.string().max(200).allow(null, "").default(null).optional(),
  po:                 Joi.string().max(200).allow(null, "").default(null).optional(),
  fa_cbm:             Joi.number().precision(4).allow(null).default(null).optional(),
  boat_company:       Joi.string().max(600).allow(null, "").default(null).optional(),
  destination:        Joi.string().max(600).allow(null, "").default(null).optional(),
  board_date:         Joi.date().allow(null).empty("").default(null).optional(),
  bl_no:              Joi.string().max(30).allow(null, "").default(null).optional(),
  sort:               Joi.string().max(30).allow(null, "").default(null).optional(),
  print_id:           Joi.string().max(30).allow(null, "").default(null).optional(),
  boat_cbm:           Joi.number().precision(4).allow(null).default(null).optional(),
  otcbm:              Joi.number().precision(4).allow(null).default(null).optional(),
  sorting_cbm:        Joi.number().precision(4).allow(null).default(null).optional(),
  co_no:              Joi.string().max(30).allow(null, "").default(null).optional(),
  el_no:              Joi.string().max(30).allow(null, "").default(null).optional(),
  elno:               Joi.string().max(30).allow(null, "").default(null).optional(),
  is_prt:             Joi.string().max(1).default("Y").optional(),
  boat_name:          Joi.string().max(200).allow(null, "").default(null).optional(),
  ar_no:              Joi.string().max(30).allow(null, "").default(null).optional(),
  ws_no:              Joi.string().max(30).allow(null, "").default(null).optional(),
  ql_date:            Joi.date().allow(null).empty("").default(null).optional(),
  gross:              Joi.number().precision(4).allow(null).default(null).optional(),
  by_out:             Joi.date().allow(null).empty("").default(null).optional(),
  docend_date:        Joi.date().allow(null).empty("").default(null).optional(),
  se_ver:             Joi.number().precision(2).allow(null).default(null).optional(),
  pack_gu:            Joi.number().precision(2).allow(null).default(null).optional(),
  ship_order:         Joi.string().max(200).allow(null, "").default(null).optional(),
  zip_invoice:        Joi.string().max(200).allow(null, "").default(null).optional(),
  invoice_no:         Joi.string().max(200).allow(null, "").default(null).optional(),
  net_weight:         Joi.number().precision(4).allow(null).default(null).optional(),
  col1:               Joi.string().max(200).allow(null, "").default(null).optional(),
  col2:               Joi.string().max(200).allow(null, "").default(null).optional(),
  col3:               Joi.string().max(200).allow(null, "").default(null).optional(),
  col4:               Joi.string().max(200).allow(null, "").default(null).optional(),
  note:               Joi.string().max(600).allow(null, "").default(null).optional(),
  status:             Joi.number().integer().default(7).optional(),
  grt_dept:           Joi.string().max(30).allow(null).empty("").default(null).optional(),
  grt_user:           Joi.string().max(30).allow(null).empty("").default(null).optional(),
  grt_date:           Joi.date().allow(null).empty("").default(null).optional(),
  last_user:          Joi.string().max(30).allow(null).empty("").default(null).optional(),
  last_date:          Joi.date().allow(null).empty("").default(null).optional(),
  locked_information: Joi.string().max(600).allow(null, "").default(null).optional(),
});

module.exports = createAcCoMSchema;