const Joi = require("joi");

const createSdOrdMSchema = Joi.object({
  org_id: Joi.string().max(6).required(),
  se_id: Joi.string().max(30).required(),
  se_seq: Joi.number().integer().required(),
  se_ver: Joi.number().integer().required(),
  se_type: Joi.string().max(8).required(),
  se_mark: Joi.string().max(1).required(),
  se_custid: Joi.string().max(10).required(),
  merchant: Joi.string().max(10).allow(null, "").optional(),
  pay_custid: Joi.string().max(10).required(),
  acc_custid: Joi.string().max(10).required(),
  po: Joi.string().max(200).allow(null, "").optional(),
  mer_po: Joi.string().max(200).allow(null, "").optional(),
  se_day: Joi.date().required(),
  prod_type: Joi.string().max(120).required(),
  curr_no: Joi.string().max(8).allow(null, "").optional(),
  se_money: Joi.number().precision(2).allow(null).empty("").optional(),
  pay_no: Joi.string().max(15).required(),
  send_mode: Joi.string().max(8).allow(null, "").optional(),
  send_addr: Joi.string().max(150).allow(null, "").optional(),
  busi_user: Joi.string().max(10).allow(null, "").optional(),
  grt_dept: Joi.string().max(8).allow(null, "").optional(),
  grt_user: Joi.string().max(10).allow(null, "").optional(),
  last_user: Joi.string().max(10).required(),
  last_date: Joi.date().default(() => new Date()).optional(),
  lead_time: Joi.number().integer().allow(null).empty("").optional(),
  is_dpoc: Joi.string().max(1).default("N").optional(),
  cicut_date: Joi.date().allow(null).empty("").optional(),
  timestamp: Joi.date().allow(null).empty("").optional(),
  sales_type: Joi.string().max(2000).allow(null, "").optional(),
  status_flag: Joi.string().max(1).allow(null, "").optional(),
  vas_date: Joi.date().allow(null).empty("").optional(),
  zipname: Joi.string().max(50).allow(null, "").optional(),
  mtf_se_id: Joi.string().max(30).allow(null, "").optional(),
  shoe_no: Joi.string().max(70).allow(null, "").optional(),
  prod_no: Joi.string().max(200).allow(null, "").optional(),
  grade: Joi.string().max(1).default("A").optional(),
  cust_lot: Joi.string().max(200).allow(null, "").optional(),
  size_type: Joi.string().max(200).allow(null, "").optional(),
  cust_sizetype: Joi.string().max(200).allow(null, "").optional(),
  pack_type: Joi.string().max(1).allow(null, "").optional(),
  flow_grp: Joi.string().max(200).allow(null, "").optional(),
  se_qty: Joi.number().precision(4).allow(null).empty("").optional(),
  b_qty: Joi.number().precision(4).allow(null).empty("").optional(),
  cr_reqdate: Joi.date().allow(null).empty("").optional(),
  nst: Joi.date().allow(null).empty("").optional(),
  nlt: Joi.date().allow(null).empty("").optional(),
  sales_price: Joi.number().precision(4).allow(null).empty("").optional(),
  sales_money: Joi.number().precision(4).allow(null).empty("").optional(),
  rebate: Joi.number().precision(2).allow(null).empty("").optional(),
  rebate_money: Joi.number().precision(2).allow(null).empty("").optional(),
  column1: Joi.string().max(70).allow(null, "").optional(),
  column2: Joi.string().max(200).allow(null, "").optional(),
  column3: Joi.string().max(200).allow(null, "").optional(),
  column4: Joi.string().max(200).allow(null, "").optional(),
  column5: Joi.string().max(200).allow(null, "").optional(),
  column6: Joi.string().max(200).allow(null, "").optional(),
  column7: Joi.string().max(200).allow(null, "").optional(),
  remark: Joi.string().max(300).allow(null, "").optional(),
  status: Joi.number().integer().required(),
  note: Joi.string().max(4000).allow(null, "").optional(),
  cur_no: Joi.string().max(15).allow(null, "").optional(),
  cr_prod: Joi.string().max(300).allow(null, "").optional(),
  delivery_date: Joi.date().allow(null).empty("").optional(),
  nst_confirm: Joi.string().max(1).default("N").optional(),
  nlt_confirm: Joi.string().max(1).default("N").optional(),
  delay_reason: Joi.string().max(8).allow(null, "").optional(),
  plan_remark: Joi.string().max(100).allow(null, "").optional(),
  sap_item_no: Joi.string().max(200).allow(null, "").optional(),
  mtf_se_seq: Joi.number().integer().allow(null).empty("").optional(),
});

module.exports = createSdOrdMSchema;